#!/bin/bash

STATE_FILE="$HOME/.config/mpd/state"
TEMP="/tmp/scroll.${BLOCK_NAME}"
DIR=`pwd`

STATE=$(grep '^state' "$STATE_FILE" | cut -d ' ' -f2)

if [ "$STATE" = "play" ]; then
    OUTPUT="  "$(/usr/bin/ncmpcpp --current-song="{{{%a - }%t}|{%f}}" --quiet | "/home/beto/.config/i3blocks/scroll" -l 25 -d '|' -t "$TEMP")
    echo "<span font_family='monospace'>${OUTPUT}</span>"
elif [ "$STATE" = "pause" ]; then
    echo "  "
else
    echo ""
fi


exit 0
