# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()
# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Use Xresources definition
import subprocess

def read_xresources(prefix):
    props = {}
    x = subprocess.run(['xrdb', '-query'], stdout=subprocess.PIPE)
    lines = x.stdout.decode().split('\n')
    for line in filter(lambda l : l.startswith(prefix), lines):
        prop, _, value = line.partition(':\t')
        props[prop] = value
    return props

xresources = read_xresources('*')
darkblack = xresources['*color0']
black = xresources['*color8']
darkred = xresources['*color1']
red = xresources['*color9']
darkgreen = xresources['*color2']
green = xresources['*color10']
darkyellow = xresources['*color3']
yellow = xresources['*color11']
darkblue = xresources['*color4']
blue = xresources['*color12']
darkmagenta = xresources['*color5']
magenta = xresources['*color13']
darkcyan = xresources['*color6']
cyan = xresources['*color14']
darkwhite = xresources['*color7']
white = xresources['*color15']

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
# Type: List of QtColor, or QtColor
c.colors.completion.fg = darkwhite

# Background color of the completion widget for odd rows.
# Type: QssColor
c.colors.completion.odd.bg = black

# Background color of the completion widget for even rows.
# Type: QssColor
c.colors.completion.even.bg = darkblack

# Foreground color of completion widget category headers.
# Type: QtColor
c.colors.completion.category.fg = darkyellow

# Background color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.bg = darkblack

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.top = darkblack

# Bottom border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.bottom = darkblack

# Foreground color of the selected completion item.
# Type: QtColor
c.colors.completion.item.selected.fg = darkblack

# Background color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.bg = darkyellow

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.item.selected.border.top = darkyellow

# Bottom border color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.border.bottom = darkyellow

# Foreground color of the matched text in the completion.
# Type: QssColor
c.colors.completion.match.fg = darkgreen

# Color of the scrollbar handle in the completion view.
# Type: QssColor
c.colors.completion.scrollbar.fg = darkwhite

# Color of the scrollbar in the completion view.
# Type: QssColor
c.colors.completion.scrollbar.bg = darkblack

# Background color for the download bar.
# Type: QssColor
c.colors.downloads.bar.bg = darkblack

# Color gradient start for download text.
# Type: QtColor
c.colors.downloads.start.fg = darkblack

# Color gradient start for download backgrounds.
# Type: QtColor
c.colors.downloads.start.bg = darkblue

# Color gradient end for download text.
# Type: QtColor
c.colors.downloads.stop.fg = darkblack

# Color gradient stop for download backgrounds.
# Type: QtColor
c.colors.downloads.stop.bg = darkcyan

# Foreground color for downloads with errors.
# Type: QtColor
c.colors.downloads.error.fg = darkred

# Font color for hints.
# Type: QssColor
c.colors.hints.fg = darkblack

# Background color for hints. Note that you can use a `rgba(...)` value
# for transparency.
# Type: QssColor
c.colors.hints.bg = darkyellow

# Font color for the matched part of hints.
# Type: QssColor
c.colors.hints.match.fg = darkwhite

# Text color for the keyhint widget.
# Type: QssColor
c.colors.keyhint.fg = darkwhite

# Highlight color for keys to complete the current keychain.
# Type: QssColor
c.colors.keyhint.suffix.fg = darkwhite

# Background color of the keyhint widget.
# Type: QssColor
c.colors.keyhint.bg = darkblack

# Foreground color of an error message.
# Type: QssColor
c.colors.messages.error.fg = darkblack

# Background color of an error message.
# Type: QssColor
c.colors.messages.error.bg = darkred

# Border color of an error message.
# Type: QssColor
c.colors.messages.error.border = darkred

# Foreground color of a warning message.
# Type: QssColor
c.colors.messages.warning.fg = darkblack

# Background color of a warning message.
# Type: QssColor
c.colors.messages.warning.bg = darkmagenta

# Border color of a warning message.
# Type: QssColor
c.colors.messages.warning.border = darkmagenta

# Foreground color of an info message.
# Type: QssColor
c.colors.messages.info.fg = darkwhite

# Background color of an info message.
# Type: QssColor
c.colors.messages.info.bg = darkblack

# Border color of an info message.
# Type: QssColor
c.colors.messages.info.border = darkblack

# Foreground color for prompts.
# Type: QssColor
c.colors.prompts.fg = darkwhite

# Border used around UI elements in prompts.
# Type: String
c.colors.prompts.border = darkblack

# Background color for prompts.
# Type: QssColor
c.colors.prompts.bg = darkblack

# Background color for the selected item in filename prompts.
# Type: QssColor
c.colors.prompts.selected.bg = darkyellow

# Foreground color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.fg = darkgreen

# Background color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.bg = darkblack

# Foreground color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.fg = darkblack

# Background color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.bg = darkblue

# Foreground color of the statusbar in passthrough mode.
# Type: QssColor
c.colors.statusbar.passthrough.fg = darkblack

# Background color of the statusbar in passthrough mode.
# Type: QssColor
c.colors.statusbar.passthrough.bg = darkcyan

# Foreground color of the statusbar in private browsing mode.
# Type: QssColor
c.colors.statusbar.private.fg = darkblack

# Background color of the statusbar in private browsing mode.
# Type: QssColor
c.colors.statusbar.private.bg = black

# Foreground color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.fg = darkwhite

# Background color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.bg = darkblack

# Foreground color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.fg = darkwhite

# Background color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.bg = darkblack

# Foreground color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.fg = darkblack

# Background color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.bg = darkmagenta

# Foreground color of the statusbar in caret mode with a selection.
# Type: QssColor
c.colors.statusbar.caret.selection.fg = darkblack

# Background color of the statusbar in caret mode with a selection.
# Type: QssColor
c.colors.statusbar.caret.selection.bg = darkblue

# Background color of the progress bar.
# Type: QssColor
c.colors.statusbar.progress.bg = darkblue

# Default foreground color of the URL in the statusbar.
# Type: QssColor
c.colors.statusbar.url.fg = darkwhite

# Foreground color of the URL in the statusbar on error.
# Type: QssColor
c.colors.statusbar.url.error.fg = darkred

# Foreground color of the URL in the statusbar for hovered links.
# Type: QssColor
c.colors.statusbar.url.hover.fg = darkwhite

# Foreground color of the URL in the statusbar on successful load
# (http).
# Type: QssColor
c.colors.statusbar.url.success.http.fg = darkcyan

# Foreground color of the URL in the statusbar on successful load
# (https).
# Type: QssColor
c.colors.statusbar.url.success.https.fg = darkgreen

# Foreground color of the URL in the statusbar when there's a warning.
# Type: QssColor
c.colors.statusbar.url.warn.fg = darkmagenta

# Background color of the tab bar.
# Type: QtColor
c.colors.tabs.bar.bg = darkblack

# Color gradient start for the tab indicator.
# Type: QtColor
c.colors.tabs.indicator.start = darkblue

# Color gradient end for the tab indicator.
# Type: QtColor
c.colors.tabs.indicator.stop = darkcyan

# Color for the tab indicator on errors.
# Type: QtColor
c.colors.tabs.indicator.error = darkred

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = darkwhite

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = black

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = darkwhite

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = darkblack

# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = darkblack

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = darkwhite

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = darkblack

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = darkwhite
