session_name: local
windows:
- layout: 83b5,221x63,0,0{110x63,0,0,0,110x63,111,0,1}
  options: {}
  panes:
  - focus: 'true'
    shell_command:
    - cd /Users/aj.vazquez/.dotfiles
    - nvim
  - shell_command:
    - cd /Users/aj.vazquez/Projects/ea
    - zsh
  window_name: nvim
- focus: 'true'
  layout: 6453,221x63,0,0{110x63,0,0,2,110x63,111,0[110x31,111,0,5,110x31,111,32,6]}
  options: {}
  panes:
  - focus: 'true'
    shell_command: python3.9
  - watch
  - zsh
  start_directory: /Users/aj.vazquez/Projects/ea
  window_name: zsh
