[aws]
symbol = "  "

[buf]
disabled = true

[c]
symbol = " "

[conda]
disabled = true

[container]
symbol = '⬢'

[dart]
disabled = true

[directory]
read_only = " "

[docker_context]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[fossil_branch]
disabled = true

[git_branch]
symbol = " "
command_timeout = 700

[golang]
symbol = " "

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[hg_branch]
disabled = true

[java]
symbol = " "

[julia]
disabled = true

[lua]
symbol = " "

[kubernetes]
symbol = "☸ "
disabled = false

[memory_usage]
symbol = " "

[meson]
disabled = true

[nim]
disabled = true

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "

[pijul_channel]
disabled = true

[python]
symbol = " "

[rlang]
disabled = true

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
disabled = true

[spack]
disabled = true

[time]
disabled = false

[zig]
symbol = '↯ '
