#!/bin/bash

# handle being called from systemd service
IMG="/tmp/lockscreen.png"
CONFIG=""
 if [ -z "$XDG_RUNTIME_DIR" ] && [ -z "$SWAYSOCK"]; then
         uid=$(id -u $USER)
         export XDG_RUNTIME_DIR="/run/user/"$uid"/"
         export SWAYSOCK=$(find $XDG_RUNTIME_DIR -iname sway*sock)
 fi

grim -o LVDS-1 $IMG
[ -f "DOTFILES/swaylock/conf" ] && CONFIG="-C $DOTFILES/swaylock/config"
if [ -f /usr/bin/convert ]; then
    mogrify -blur 0x6 -swirl 360 $IMG
    swaylock -f -i $IMG "$CONFIG"
else
    swaylock -f -c 000000 "$CONFIG"
fi
