#!/bin/bash

NOTMUCH=/usr/bin/notmuch

"$NOTMUCH" new --quiet
"$NOTMUCH" tag +inbox +unread -new +gmail -- folder:gmail/INBOX and tag:new
"$NOTMUCH" tag +inbox +unread -new +zoho -- folder:zoho/INBOX and tag:new
"$NOTMUCH" tag +inbox +unread -new +supmoldie -- folder:supmoldie/INBOX and tag:new

"$NOTMUCH" tag -inbox -unread +sent +zoho -- from:aj.vazquez@zoho.com and not tag:sent
"$NOTMUCH" tag -inbox -unread +sent +gmail -- from:beto.v25@gmail.com and not tag:sent
"$NOTMUCH" tag -inbox -unread +sent +supmoldie -- from:a.vazquez@supmoldie.com and not tag:sent

"$NOTMUCH" tag -inbox -unread +archive +zoho -- folder:zoho/archive and not tag:archive
"$NOTMUCH" tag -inbox -unread +archive +supmoldie -- folder:supmoldie/archive and tag:archive
"$NOTMUCH" tag -inbox -unread +archive +gmail -- folder:gmail/starred and not tag:archive

"$NOTMUCH" tag -inbox -unread -sent +draft +gmail -- folder:gmail/drafts and not tag:draft
"$NOTMUCH" tag -inbox -unread -sent +draft +zoho -- folder:zoho/drafts and not tag:draft
"$NOTMUCH" tag -inbox -unread -sent +draft +supmoldie -- folder:supmoldie/drafts and not tag:draft

"$NOTMUCH" tag -inbox -unread +trash +gmail -- folder:gmail/trash and not tag:trash
"$NOTMUCH" tag -inbox -unread +trash +zoho -- folder:zoho/trash and not tag:trash
"$NOTMUCH" tag -inbox -unread +trash +supmoldie -- folder:supmoldie/trash and not tag:trash

"$NOTMUCH" tag -inbox -unread +spam +gmail -- folder:gmail/junk and not tag:spam
"$NOTMUCH" tag -inbox -unread +spam +zoho -- folder:zoho/junk and not tag:spam
"$NOTMUCH" tag -inbox -unread +spam +supmoldie -- folder:supmoldie/junk and not tag:spam
