#!/usr/bin/env bash

LOCKER="$DOTFILES/scripts/lockscreen"

option="$(</dev/stdin)"

if [ ${#option} -gt 0 ]
then
    case $option in
      Reboot)
        echo 'reboot'
        # systemctl reboot
        ;;
	Shutdown)
        echo 'shutdown'
        # systemctl poweroff
        ;;
      Suspend)
        echo 'suspend'
        # systemctl suspend
        ;;
      Lock)
        echo 'lock'
        # "$LOCKER"
        ;;
      *)
        ;;
    esac
fi
