#!/usr/bin/env bash

LOCKER="$DOTFILES/scripts/lockscreen"

option="$(</dev/stdin)"

if [ ${#option} -gt 0 ]
then
    case $option in
      Reboot)
        systemctl reboot
        ;;
	Shutdown)
        systemctl poweroff
        ;;
      Suspend)
        systemctl suspend
        ;;
      Lock)
        "$LOCKER"
        ;;
      *)
        ;;
    esac
fi
