#!/bin/bash
 
# Base directory for password files
DIR="$HOME/.config/neomutt"

# Declaration of array
declare -A SERVERS
declare -A SERVER

SERVER["HOST"]='imap.gmail.com'
SERVER["USER"]='beto.v25@gmail.com'
SERVER["FILE"]="$DIR/gmail.password.gpg"
SERVER["HAMBOX"]='INBOX'
SERVER["SPAMBOX"]='[Gmail]/Spam'

string=$(declare -p SERVER)
SERVERS["1"]=${string}

SERVER["HOST"]='imap.zoho.com'
SERVER["USER"]='aj.vazquez@zoho.com'
SERVER["FILE"]="$DIR/zoho.password.gpg"
SERVER["HAMBOX"]='INBOX'
SERVER["SPAMBOX"]='Spam'

string=$(declare -p SERVER)
SERVERS["2"]=${string}

SERVER["HOST"]='gator3197.hostgator.com'
SERVER["USER"]='a.vazquez@supmoldie.com'
SERVER["FILE"]="$DIR/supmoldie.password.gpg"
SERVER["HAMBOX"]='INBOX'
SERVER["SPAMBOX"]='Inbox.spam'

string=$(declare -p SERVER)
SERVERS["3"]=${string}

# Loop on array elements
for key in "${!SERVERS[@]}"; do
   eval "${SERVERS["$key"]}"
   if [ -f "${SERVER[FILE]}" ]; then
       /usr/bin/isbg --imaphost "${SERVER[HOST]}" --imapuser "${SERVER[USER]}" --imappasswd $(gpg --quiet --for-your-eyes-only --no-tty --decrypt "${SERVER[FILE]}") --spaminbox "${SERVER[SPAMBOX]}" --learnhambox "${SERVER[SPAMBOX]}" --learnspambox "${SERVER[SPAMBOX]}" --spamc --delete --expunge "$@"
   fi
done
