# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# alias k='kubectl'
alias ksys='kubectl --namespace=kube-system'
alias ka='kubectl apply --recursive -f'
alias ksysa='kubectl --namespace=kube-system apply --recursive -f'
alias kak='kubectl apply -k'
alias kk='kubectl kustomize'
alias kex='kubectl exec -i -t'
alias ksysex='kubectl --namespace=kube-system exec -i -t'
alias klo='kubectl logs -f'
alias ksyslo='kubectl --namespace=kube-system logs -f'
alias klop='kubectl logs -f -p'
alias ksyslop='kubectl --namespace=kube-system logs -f -p'
alias kp='kubectl proxy'
alias kpf='kubectl port-forward'
alias kg='kubectl get'
alias ksysg='kubectl --namespace=kube-system get'
alias kd='kubectl describe'
alias ksysd='kubectl --namespace=kube-system describe'
alias krm='kubectl delete'
alias ksysrm='kubectl --namespace=kube-system delete'
alias krun='kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias ksysrun='kubectl --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias kgpo='kubectl get pods'
alias ksysgpo='kubectl --namespace=kube-system get pods'
alias kdpo='kubectl describe pods'
alias ksysdpo='kubectl --namespace=kube-system describe pods'
alias krmpo='kubectl delete pods'
alias ksysrmpo='kubectl --namespace=kube-system delete pods'
alias kgdep='kubectl get deployment'
alias ksysgdep='kubectl --namespace=kube-system get deployment'
alias kddep='kubectl describe deployment'
alias ksysddep='kubectl --namespace=kube-system describe deployment'
alias krmdep='kubectl delete deployment'
alias ksysrmdep='kubectl --namespace=kube-system delete deployment'
alias kgsts='kubectl get statefulset'
alias ksysgsts='kubectl --namespace=kube-system get statefulset'
alias kdsts='kubectl describe statefulset'
alias ksysdsts='kubectl --namespace=kube-system describe statefulset'
alias krmsts='kubectl delete statefulset'
alias ksysrmsts='kubectl --namespace=kube-system delete statefulset'
alias kgsvc='kubectl get service'
alias ksysgsvc='kubectl --namespace=kube-system get service'
alias kdsvc='kubectl describe service'
alias ksysdsvc='kubectl --namespace=kube-system describe service'
alias krmsvc='kubectl delete service'
alias ksysrmsvc='kubectl --namespace=kube-system delete service'
alias kging='kubectl get ingress'
alias ksysging='kubectl --namespace=kube-system get ingress'
alias kding='kubectl describe ingress'
alias ksysding='kubectl --namespace=kube-system describe ingress'
alias krming='kubectl delete ingress'
alias ksysrming='kubectl --namespace=kube-system delete ingress'
alias kgcm='kubectl get configmap'
alias ksysgcm='kubectl --namespace=kube-system get configmap'
alias kdcm='kubectl describe configmap'
alias ksysdcm='kubectl --namespace=kube-system describe configmap'
alias krmcm='kubectl delete configmap'
alias ksysrmcm='kubectl --namespace=kube-system delete configmap'
alias kgsec='kubectl get secret'
alias ksysgsec='kubectl --namespace=kube-system get secret'
alias kdsec='kubectl describe secret'
alias ksysdsec='kubectl --namespace=kube-system describe secret'
alias krmsec='kubectl delete secret'
alias ksysrmsec='kubectl --namespace=kube-system delete secret'
alias kgno='kubectl get nodes'
alias kdno='kubectl describe nodes'
alias kgns='kubectl get namespaces'
alias kdns='kubectl describe namespaces'
alias krmns='kubectl delete namespaces'
alias kgoyaml='kubectl get -o=yaml'
alias ksysgoyaml='kubectl --namespace=kube-system get -o=yaml'
alias kgpooyaml='kubectl get pods -o=yaml'
alias ksysgpooyaml='kubectl --namespace=kube-system get pods -o=yaml'
alias kgdepoyaml='kubectl get deployment -o=yaml'
alias ksysgdepoyaml='kubectl --namespace=kube-system get deployment -o=yaml'
alias kgstsoyaml='kubectl get statefulset -o=yaml'
alias ksysgstsoyaml='kubectl --namespace=kube-system get statefulset -o=yaml'
alias kgsvcoyaml='kubectl get service -o=yaml'
alias ksysgsvcoyaml='kubectl --namespace=kube-system get service -o=yaml'
alias kgingoyaml='kubectl get ingress -o=yaml'
alias ksysgingoyaml='kubectl --namespace=kube-system get ingress -o=yaml'
alias kgcmoyaml='kubectl get configmap -o=yaml'
alias ksysgcmoyaml='kubectl --namespace=kube-system get configmap -o=yaml'
alias kgsecoyaml='kubectl get secret -o=yaml'
alias ksysgsecoyaml='kubectl --namespace=kube-system get secret -o=yaml'
alias kgnooyaml='kubectl get nodes -o=yaml'
alias kgnsoyaml='kubectl get namespaces -o=yaml'
alias kgowide='kubectl get -o=wide'
alias ksysgowide='kubectl --namespace=kube-system get -o=wide'
alias kgpoowide='kubectl get pods -o=wide'
alias ksysgpoowide='kubectl --namespace=kube-system get pods -o=wide'
alias kgdepowide='kubectl get deployment -o=wide'
alias ksysgdepowide='kubectl --namespace=kube-system get deployment -o=wide'
alias kgstsowide='kubectl get statefulset -o=wide'
alias ksysgstsowide='kubectl --namespace=kube-system get statefulset -o=wide'
alias kgsvcowide='kubectl get service -o=wide'
alias ksysgsvcowide='kubectl --namespace=kube-system get service -o=wide'
alias kgingowide='kubectl get ingress -o=wide'
alias ksysgingowide='kubectl --namespace=kube-system get ingress -o=wide'
alias kgcmowide='kubectl get configmap -o=wide'
alias ksysgcmowide='kubectl --namespace=kube-system get configmap -o=wide'
alias kgsecowide='kubectl get secret -o=wide'
alias ksysgsecowide='kubectl --namespace=kube-system get secret -o=wide'
alias kgnoowide='kubectl get nodes -o=wide'
alias kgnsowide='kubectl get namespaces -o=wide'
alias kgojson='kubectl get -o=json'
alias ksysgojson='kubectl --namespace=kube-system get -o=json'
alias kgpoojson='kubectl get pods -o=json'
alias ksysgpoojson='kubectl --namespace=kube-system get pods -o=json'
alias kgdepojson='kubectl get deployment -o=json'
alias ksysgdepojson='kubectl --namespace=kube-system get deployment -o=json'
alias kgstsojson='kubectl get statefulset -o=json'
alias ksysgstsojson='kubectl --namespace=kube-system get statefulset -o=json'
alias kgsvcojson='kubectl get service -o=json'
alias ksysgsvcojson='kubectl --namespace=kube-system get service -o=json'
alias kgingojson='kubectl get ingress -o=json'
alias ksysgingojson='kubectl --namespace=kube-system get ingress -o=json'
alias kgcmojson='kubectl get configmap -o=json'
alias ksysgcmojson='kubectl --namespace=kube-system get configmap -o=json'
alias kgsecojson='kubectl get secret -o=json'
alias ksysgsecojson='kubectl --namespace=kube-system get secret -o=json'
alias kgnoojson='kubectl get nodes -o=json'
alias kgnsojson='kubectl get namespaces -o=json'
alias kgall='kubectl get --all-namespaces'
alias kdall='kubectl describe --all-namespaces'
alias kgpoall='kubectl get pods --all-namespaces'
alias kdpoall='kubectl describe pods --all-namespaces'
alias kgdepall='kubectl get deployment --all-namespaces'
alias kddepall='kubectl describe deployment --all-namespaces'
alias kgstsall='kubectl get statefulset --all-namespaces'
alias kdstsall='kubectl describe statefulset --all-namespaces'
alias kgsvcall='kubectl get service --all-namespaces'
alias kdsvcall='kubectl describe service --all-namespaces'
alias kgingall='kubectl get ingress --all-namespaces'
alias kdingall='kubectl describe ingress --all-namespaces'
alias kgcmall='kubectl get configmap --all-namespaces'
alias kdcmall='kubectl describe configmap --all-namespaces'
alias kgsecall='kubectl get secret --all-namespaces'
alias kdsecall='kubectl describe secret --all-namespaces'
alias kgnsall='kubectl get namespaces --all-namespaces'
alias kdnsall='kubectl describe namespaces --all-namespaces'
alias kgsl='kubectl get --show-labels'
alias ksysgsl='kubectl --namespace=kube-system get --show-labels'
alias kgposl='kubectl get pods --show-labels'
alias ksysgposl='kubectl --namespace=kube-system get pods --show-labels'
alias kgdepsl='kubectl get deployment --show-labels'
alias ksysgdepsl='kubectl --namespace=kube-system get deployment --show-labels'
alias kgstssl='kubectl get statefulset --show-labels'
alias ksysgstssl='kubectl --namespace=kube-system get statefulset --show-labels'
alias kgsvcsl='kubectl get service --show-labels'
alias ksysgsvcsl='kubectl --namespace=kube-system get service --show-labels'
alias kgingsl='kubectl get ingress --show-labels'
alias ksysgingsl='kubectl --namespace=kube-system get ingress --show-labels'
alias kgcmsl='kubectl get configmap --show-labels'
alias ksysgcmsl='kubectl --namespace=kube-system get configmap --show-labels'
alias kgsecsl='kubectl get secret --show-labels'
alias ksysgsecsl='kubectl --namespace=kube-system get secret --show-labels'
alias kgnosl='kubectl get nodes --show-labels'
alias kgnssl='kubectl get namespaces --show-labels'
alias krmall='kubectl delete --all'
alias ksysrmall='kubectl --namespace=kube-system delete --all'
alias krmpoall='kubectl delete pods --all'
alias ksysrmpoall='kubectl --namespace=kube-system delete pods --all'
alias krmdepall='kubectl delete deployment --all'
alias ksysrmdepall='kubectl --namespace=kube-system delete deployment --all'
alias krmstsall='kubectl delete statefulset --all'
alias ksysrmstsall='kubectl --namespace=kube-system delete statefulset --all'
alias krmsvcall='kubectl delete service --all'
alias ksysrmsvcall='kubectl --namespace=kube-system delete service --all'
alias krmingall='kubectl delete ingress --all'
alias ksysrmingall='kubectl --namespace=kube-system delete ingress --all'
alias krmcmall='kubectl delete configmap --all'
alias ksysrmcmall='kubectl --namespace=kube-system delete configmap --all'
alias krmsecall='kubectl delete secret --all'
alias ksysrmsecall='kubectl --namespace=kube-system delete secret --all'
alias krmnsall='kubectl delete namespaces --all'
alias kgw='watch kubectl get'
alias ksysgw='watch kubectl --namespace=kube-system get'
alias kgpow='watch kubectl get pods'
alias ksysgpow='watch kubectl --namespace=kube-system get pods'
alias kgdepw='watch kubectl get deployment'
alias ksysgdepw='watch kubectl --namespace=kube-system get deployment'
alias kgstsw='watch kubectl get statefulset'
alias ksysgstsw='watch kubectl --namespace=kube-system get statefulset'
alias kgsvcw='watch kubectl get service'
alias ksysgsvcw='watch kubectl --namespace=kube-system get service'
alias kgingw='watch kubectl get ingress'
alias ksysgingw='watch kubectl --namespace=kube-system get ingress'
alias kgcmw='watch kubectl get configmap'
alias ksysgcmw='watch kubectl --namespace=kube-system get configmap'
alias kgsecw='watch kubectl get secret'
alias ksysgsecw='watch kubectl --namespace=kube-system get secret'
alias kgnow='watch kubectl get nodes'
alias kgnsw='watch kubectl get namespaces'
alias kgoyamlall='kubectl get -o=yaml --all-namespaces'
alias kgpooyamlall='kubectl get pods -o=yaml --all-namespaces'
alias kgdepoyamlall='kubectl get deployment -o=yaml --all-namespaces'
alias kgstsoyamlall='kubectl get statefulset -o=yaml --all-namespaces'
alias kgsvcoyamlall='kubectl get service -o=yaml --all-namespaces'
alias kgingoyamlall='kubectl get ingress -o=yaml --all-namespaces'
alias kgcmoyamlall='kubectl get configmap -o=yaml --all-namespaces'
alias kgsecoyamlall='kubectl get secret -o=yaml --all-namespaces'
alias kgnsoyamlall='kubectl get namespaces -o=yaml --all-namespaces'
alias kgalloyaml='kubectl get --all-namespaces -o=yaml'
alias kgpoalloyaml='kubectl get pods --all-namespaces -o=yaml'
alias kgdepalloyaml='kubectl get deployment --all-namespaces -o=yaml'
alias kgstsalloyaml='kubectl get statefulset --all-namespaces -o=yaml'
alias kgsvcalloyaml='kubectl get service --all-namespaces -o=yaml'
alias kgingalloyaml='kubectl get ingress --all-namespaces -o=yaml'
alias kgcmalloyaml='kubectl get configmap --all-namespaces -o=yaml'
alias kgsecalloyaml='kubectl get secret --all-namespaces -o=yaml'
alias kgnsalloyaml='kubectl get namespaces --all-namespaces -o=yaml'
alias kgwoyaml='watch kubectl get -o=yaml'
alias ksysgwoyaml='watch kubectl --namespace=kube-system get -o=yaml'
alias kgpowoyaml='watch kubectl get pods -o=yaml'
alias ksysgpowoyaml='watch kubectl --namespace=kube-system get pods -o=yaml'
alias kgdepwoyaml='watch kubectl get deployment -o=yaml'
alias ksysgdepwoyaml='watch kubectl --namespace=kube-system get deployment -o=yaml'
alias kgstswoyaml='watch kubectl get statefulset -o=yaml'
alias ksysgstswoyaml='watch kubectl --namespace=kube-system get statefulset -o=yaml'
alias kgsvcwoyaml='watch kubectl get service -o=yaml'
alias ksysgsvcwoyaml='watch kubectl --namespace=kube-system get service -o=yaml'
alias kgingwoyaml='watch kubectl get ingress -o=yaml'
alias ksysgingwoyaml='watch kubectl --namespace=kube-system get ingress -o=yaml'
alias kgcmwoyaml='watch kubectl get configmap -o=yaml'
alias ksysgcmwoyaml='watch kubectl --namespace=kube-system get configmap -o=yaml'
alias kgsecwoyaml='watch kubectl get secret -o=yaml'
alias ksysgsecwoyaml='watch kubectl --namespace=kube-system get secret -o=yaml'
alias kgnowoyaml='watch kubectl get nodes -o=yaml'
alias kgnswoyaml='watch kubectl get namespaces -o=yaml'
alias kgowideall='kubectl get -o=wide --all-namespaces'
alias kgpoowideall='kubectl get pods -o=wide --all-namespaces'
alias kgdepowideall='kubectl get deployment -o=wide --all-namespaces'
alias kgstsowideall='kubectl get statefulset -o=wide --all-namespaces'
alias kgsvcowideall='kubectl get service -o=wide --all-namespaces'
alias kgingowideall='kubectl get ingress -o=wide --all-namespaces'
alias kgcmowideall='kubectl get configmap -o=wide --all-namespaces'
alias kgsecowideall='kubectl get secret -o=wide --all-namespaces'
alias kgnsowideall='kubectl get namespaces -o=wide --all-namespaces'
alias kgallowide='kubectl get --all-namespaces -o=wide'
alias kgpoallowide='kubectl get pods --all-namespaces -o=wide'
alias kgdepallowide='kubectl get deployment --all-namespaces -o=wide'
alias kgstsallowide='kubectl get statefulset --all-namespaces -o=wide'
alias kgsvcallowide='kubectl get service --all-namespaces -o=wide'
alias kgingallowide='kubectl get ingress --all-namespaces -o=wide'
alias kgcmallowide='kubectl get configmap --all-namespaces -o=wide'
alias kgsecallowide='kubectl get secret --all-namespaces -o=wide'
alias kgnsallowide='kubectl get namespaces --all-namespaces -o=wide'
alias kgowidesl='kubectl get -o=wide --show-labels'
alias ksysgowidesl='kubectl --namespace=kube-system get -o=wide --show-labels'
alias kgpoowidesl='kubectl get pods -o=wide --show-labels'
alias ksysgpoowidesl='kubectl --namespace=kube-system get pods -o=wide --show-labels'
alias kgdepowidesl='kubectl get deployment -o=wide --show-labels'
alias ksysgdepowidesl='kubectl --namespace=kube-system get deployment -o=wide --show-labels'
alias kgstsowidesl='kubectl get statefulset -o=wide --show-labels'
alias ksysgstsowidesl='kubectl --namespace=kube-system get statefulset -o=wide --show-labels'
alias kgsvcowidesl='kubectl get service -o=wide --show-labels'
alias ksysgsvcowidesl='kubectl --namespace=kube-system get service -o=wide --show-labels'
alias kgingowidesl='kubectl get ingress -o=wide --show-labels'
alias ksysgingowidesl='kubectl --namespace=kube-system get ingress -o=wide --show-labels'
alias kgcmowidesl='kubectl get configmap -o=wide --show-labels'
alias ksysgcmowidesl='kubectl --namespace=kube-system get configmap -o=wide --show-labels'
alias kgsecowidesl='kubectl get secret -o=wide --show-labels'
alias ksysgsecowidesl='kubectl --namespace=kube-system get secret -o=wide --show-labels'
alias kgnoowidesl='kubectl get nodes -o=wide --show-labels'
alias kgnsowidesl='kubectl get namespaces -o=wide --show-labels'
alias kgslowide='kubectl get --show-labels -o=wide'
alias ksysgslowide='kubectl --namespace=kube-system get --show-labels -o=wide'
alias kgposlowide='kubectl get pods --show-labels -o=wide'
alias ksysgposlowide='kubectl --namespace=kube-system get pods --show-labels -o=wide'
alias kgdepslowide='kubectl get deployment --show-labels -o=wide'
alias ksysgdepslowide='kubectl --namespace=kube-system get deployment --show-labels -o=wide'
alias kgstsslowide='kubectl get statefulset --show-labels -o=wide'
alias ksysgstsslowide='kubectl --namespace=kube-system get statefulset --show-labels -o=wide'
alias kgsvcslowide='kubectl get service --show-labels -o=wide'
alias ksysgsvcslowide='kubectl --namespace=kube-system get service --show-labels -o=wide'
alias kgingslowide='kubectl get ingress --show-labels -o=wide'
alias ksysgingslowide='kubectl --namespace=kube-system get ingress --show-labels -o=wide'
alias kgcmslowide='kubectl get configmap --show-labels -o=wide'
alias ksysgcmslowide='kubectl --namespace=kube-system get configmap --show-labels -o=wide'
alias kgsecslowide='kubectl get secret --show-labels -o=wide'
alias ksysgsecslowide='kubectl --namespace=kube-system get secret --show-labels -o=wide'
alias kgnoslowide='kubectl get nodes --show-labels -o=wide'
alias kgnsslowide='kubectl get namespaces --show-labels -o=wide'
alias kgwowide='watch kubectl get -o=wide'
alias ksysgwowide='watch kubectl --namespace=kube-system get -o=wide'
alias kgpowowide='watch kubectl get pods -o=wide'
alias ksysgpowowide='watch kubectl --namespace=kube-system get pods -o=wide'
alias kgdepwowide='watch kubectl get deployment -o=wide'
alias ksysgdepwowide='watch kubectl --namespace=kube-system get deployment -o=wide'
alias kgstswowide='watch kubectl get statefulset -o=wide'
alias ksysgstswowide='watch kubectl --namespace=kube-system get statefulset -o=wide'
alias kgsvcwowide='watch kubectl get service -o=wide'
alias ksysgsvcwowide='watch kubectl --namespace=kube-system get service -o=wide'
alias kgingwowide='watch kubectl get ingress -o=wide'
alias ksysgingwowide='watch kubectl --namespace=kube-system get ingress -o=wide'
alias kgcmwowide='watch kubectl get configmap -o=wide'
alias ksysgcmwowide='watch kubectl --namespace=kube-system get configmap -o=wide'
alias kgsecwowide='watch kubectl get secret -o=wide'
alias ksysgsecwowide='watch kubectl --namespace=kube-system get secret -o=wide'
alias kgnowowide='watch kubectl get nodes -o=wide'
alias kgnswowide='watch kubectl get namespaces -o=wide'
alias kgojsonall='kubectl get -o=json --all-namespaces'
alias kgpoojsonall='kubectl get pods -o=json --all-namespaces'
alias kgdepojsonall='kubectl get deployment -o=json --all-namespaces'
alias kgstsojsonall='kubectl get statefulset -o=json --all-namespaces'
alias kgsvcojsonall='kubectl get service -o=json --all-namespaces'
alias kgingojsonall='kubectl get ingress -o=json --all-namespaces'
alias kgcmojsonall='kubectl get configmap -o=json --all-namespaces'
alias kgsecojsonall='kubectl get secret -o=json --all-namespaces'
alias kgnsojsonall='kubectl get namespaces -o=json --all-namespaces'
alias kgallojson='kubectl get --all-namespaces -o=json'
alias kgpoallojson='kubectl get pods --all-namespaces -o=json'
alias kgdepallojson='kubectl get deployment --all-namespaces -o=json'
alias kgstsallojson='kubectl get statefulset --all-namespaces -o=json'
alias kgsvcallojson='kubectl get service --all-namespaces -o=json'
alias kgingallojson='kubectl get ingress --all-namespaces -o=json'
alias kgcmallojson='kubectl get configmap --all-namespaces -o=json'
alias kgsecallojson='kubectl get secret --all-namespaces -o=json'
alias kgnsallojson='kubectl get namespaces --all-namespaces -o=json'
alias kgwojson='watch kubectl get -o=json'
alias ksysgwojson='watch kubectl --namespace=kube-system get -o=json'
alias kgpowojson='watch kubectl get pods -o=json'
alias ksysgpowojson='watch kubectl --namespace=kube-system get pods -o=json'
alias kgdepwojson='watch kubectl get deployment -o=json'
alias ksysgdepwojson='watch kubectl --namespace=kube-system get deployment -o=json'
alias kgstswojson='watch kubectl get statefulset -o=json'
alias ksysgstswojson='watch kubectl --namespace=kube-system get statefulset -o=json'
alias kgsvcwojson='watch kubectl get service -o=json'
alias ksysgsvcwojson='watch kubectl --namespace=kube-system get service -o=json'
alias kgingwojson='watch kubectl get ingress -o=json'
alias ksysgingwojson='watch kubectl --namespace=kube-system get ingress -o=json'
alias kgcmwojson='watch kubectl get configmap -o=json'
alias ksysgcmwojson='watch kubectl --namespace=kube-system get configmap -o=json'
alias kgsecwojson='watch kubectl get secret -o=json'
alias ksysgsecwojson='watch kubectl --namespace=kube-system get secret -o=json'
alias kgnowojson='watch kubectl get nodes -o=json'
alias kgnswojson='watch kubectl get namespaces -o=json'
alias kgallsl='kubectl get --all-namespaces --show-labels'
alias kgpoallsl='kubectl get pods --all-namespaces --show-labels'
alias kgdepallsl='kubectl get deployment --all-namespaces --show-labels'
alias kgstsallsl='kubectl get statefulset --all-namespaces --show-labels'
alias kgsvcallsl='kubectl get service --all-namespaces --show-labels'
alias kgingallsl='kubectl get ingress --all-namespaces --show-labels'
alias kgcmallsl='kubectl get configmap --all-namespaces --show-labels'
alias kgsecallsl='kubectl get secret --all-namespaces --show-labels'
alias kgnsallsl='kubectl get namespaces --all-namespaces --show-labels'
alias kgslall='kubectl get --show-labels --all-namespaces'
alias kgposlall='kubectl get pods --show-labels --all-namespaces'
alias kgdepslall='kubectl get deployment --show-labels --all-namespaces'
alias kgstsslall='kubectl get statefulset --show-labels --all-namespaces'
alias kgsvcslall='kubectl get service --show-labels --all-namespaces'
alias kgingslall='kubectl get ingress --show-labels --all-namespaces'
alias kgcmslall='kubectl get configmap --show-labels --all-namespaces'
alias kgsecslall='kubectl get secret --show-labels --all-namespaces'
alias kgnsslall='kubectl get namespaces --show-labels --all-namespaces'
alias kgallw='watch kubectl get --all-namespaces'
alias kgpoallw='watch kubectl get pods --all-namespaces'
alias kgdepallw='watch kubectl get deployment --all-namespaces'
alias kgstsallw='watch kubectl get statefulset --all-namespaces'
alias kgsvcallw='watch kubectl get service --all-namespaces'
alias kgingallw='watch kubectl get ingress --all-namespaces'
alias kgcmallw='watch kubectl get configmap --all-namespaces'
alias kgsecallw='watch kubectl get secret --all-namespaces'
alias kgnsallw='watch kubectl get namespaces --all-namespaces'
alias kgwall='watch kubectl get --all-namespaces'
alias kgpowall='watch kubectl get pods --all-namespaces'
alias kgdepwall='watch kubectl get deployment --all-namespaces'
alias kgstswall='watch kubectl get statefulset --all-namespaces'
alias kgsvcwall='watch kubectl get service --all-namespaces'
alias kgingwall='watch kubectl get ingress --all-namespaces'
alias kgcmwall='watch kubectl get configmap --all-namespaces'
alias kgsecwall='watch kubectl get secret --all-namespaces'
alias kgnswall='watch kubectl get namespaces --all-namespaces'
alias kgslw='watch kubectl get --show-labels'
alias ksysgslw='watch kubectl --namespace=kube-system get --show-labels'
alias kgposlw='watch kubectl get pods --show-labels'
alias ksysgposlw='watch kubectl --namespace=kube-system get pods --show-labels'
alias kgdepslw='watch kubectl get deployment --show-labels'
alias ksysgdepslw='watch kubectl --namespace=kube-system get deployment --show-labels'
alias kgstsslw='watch kubectl get statefulset --show-labels'
alias ksysgstsslw='watch kubectl --namespace=kube-system get statefulset --show-labels'
alias kgsvcslw='watch kubectl get service --show-labels'
alias ksysgsvcslw='watch kubectl --namespace=kube-system get service --show-labels'
alias kgingslw='watch kubectl get ingress --show-labels'
alias ksysgingslw='watch kubectl --namespace=kube-system get ingress --show-labels'
alias kgcmslw='watch kubectl get configmap --show-labels'
alias ksysgcmslw='watch kubectl --namespace=kube-system get configmap --show-labels'
alias kgsecslw='watch kubectl get secret --show-labels'
alias ksysgsecslw='watch kubectl --namespace=kube-system get secret --show-labels'
alias kgnoslw='watch kubectl get nodes --show-labels'
alias kgnsslw='watch kubectl get namespaces --show-labels'
alias kgwsl='watch kubectl get --show-labels'
alias ksysgwsl='watch kubectl --namespace=kube-system get --show-labels'
alias kgpowsl='watch kubectl get pods --show-labels'
alias ksysgpowsl='watch kubectl --namespace=kube-system get pods --show-labels'
alias kgdepwsl='watch kubectl get deployment --show-labels'
alias ksysgdepwsl='watch kubectl --namespace=kube-system get deployment --show-labels'
alias kgstswsl='watch kubectl get statefulset --show-labels'
alias ksysgstswsl='watch kubectl --namespace=kube-system get statefulset --show-labels'
alias kgsvcwsl='watch kubectl get service --show-labels'
alias ksysgsvcwsl='watch kubectl --namespace=kube-system get service --show-labels'
alias kgingwsl='watch kubectl get ingress --show-labels'
alias ksysgingwsl='watch kubectl --namespace=kube-system get ingress --show-labels'
alias kgcmwsl='watch kubectl get configmap --show-labels'
alias ksysgcmwsl='watch kubectl --namespace=kube-system get configmap --show-labels'
alias kgsecwsl='watch kubectl get secret --show-labels'
alias ksysgsecwsl='watch kubectl --namespace=kube-system get secret --show-labels'
alias kgnowsl='watch kubectl get nodes --show-labels'
alias kgnswsl='watch kubectl get namespaces --show-labels'
alias kgallwoyaml='watch kubectl get --all-namespaces -o=yaml'
alias kgpoallwoyaml='watch kubectl get pods --all-namespaces -o=yaml'
alias kgdepallwoyaml='watch kubectl get deployment --all-namespaces -o=yaml'
alias kgstsallwoyaml='watch kubectl get statefulset --all-namespaces -o=yaml'
alias kgsvcallwoyaml='watch kubectl get service --all-namespaces -o=yaml'
alias kgingallwoyaml='watch kubectl get ingress --all-namespaces -o=yaml'
alias kgcmallwoyaml='watch kubectl get configmap --all-namespaces -o=yaml'
alias kgsecallwoyaml='watch kubectl get secret --all-namespaces -o=yaml'
alias kgnsallwoyaml='watch kubectl get namespaces --all-namespaces -o=yaml'
alias kgwoyamlall='watch kubectl get -o=yaml --all-namespaces'
alias kgpowoyamlall='watch kubectl get pods -o=yaml --all-namespaces'
alias kgdepwoyamlall='watch kubectl get deployment -o=yaml --all-namespaces'
alias kgstswoyamlall='watch kubectl get statefulset -o=yaml --all-namespaces'
alias kgsvcwoyamlall='watch kubectl get service -o=yaml --all-namespaces'
alias kgingwoyamlall='watch kubectl get ingress -o=yaml --all-namespaces'
alias kgcmwoyamlall='watch kubectl get configmap -o=yaml --all-namespaces'
alias kgsecwoyamlall='watch kubectl get secret -o=yaml --all-namespaces'
alias kgnswoyamlall='watch kubectl get namespaces -o=yaml --all-namespaces'
alias kgwalloyaml='watch kubectl get --all-namespaces -o=yaml'
alias kgpowalloyaml='watch kubectl get pods --all-namespaces -o=yaml'
alias kgdepwalloyaml='watch kubectl get deployment --all-namespaces -o=yaml'
alias kgstswalloyaml='watch kubectl get statefulset --all-namespaces -o=yaml'
alias kgsvcwalloyaml='watch kubectl get service --all-namespaces -o=yaml'
alias kgingwalloyaml='watch kubectl get ingress --all-namespaces -o=yaml'
alias kgcmwalloyaml='watch kubectl get configmap --all-namespaces -o=yaml'
alias kgsecwalloyaml='watch kubectl get secret --all-namespaces -o=yaml'
alias kgnswalloyaml='watch kubectl get namespaces --all-namespaces -o=yaml'
alias kgowideallsl='kubectl get -o=wide --all-namespaces --show-labels'
alias kgpoowideallsl='kubectl get pods -o=wide --all-namespaces --show-labels'
alias kgdepowideallsl='kubectl get deployment -o=wide --all-namespaces --show-labels'
alias kgstsowideallsl='kubectl get statefulset -o=wide --all-namespaces --show-labels'
alias kgsvcowideallsl='kubectl get service -o=wide --all-namespaces --show-labels'
alias kgingowideallsl='kubectl get ingress -o=wide --all-namespaces --show-labels'
alias kgcmowideallsl='kubectl get configmap -o=wide --all-namespaces --show-labels'
alias kgsecowideallsl='kubectl get secret -o=wide --all-namespaces --show-labels'
alias kgnsowideallsl='kubectl get namespaces -o=wide --all-namespaces --show-labels'
alias kgowideslall='kubectl get -o=wide --show-labels --all-namespaces'
alias kgpoowideslall='kubectl get pods -o=wide --show-labels --all-namespaces'
alias kgdepowideslall='kubectl get deployment -o=wide --show-labels --all-namespaces'
alias kgstsowideslall='kubectl get statefulset -o=wide --show-labels --all-namespaces'
alias kgsvcowideslall='kubectl get service -o=wide --show-labels --all-namespaces'
alias kgingowideslall='kubectl get ingress -o=wide --show-labels --all-namespaces'
alias kgcmowideslall='kubectl get configmap -o=wide --show-labels --all-namespaces'
alias kgsecowideslall='kubectl get secret -o=wide --show-labels --all-namespaces'
alias kgnsowideslall='kubectl get namespaces -o=wide --show-labels --all-namespaces'
alias kgallowidesl='kubectl get --all-namespaces -o=wide --show-labels'
alias kgpoallowidesl='kubectl get pods --all-namespaces -o=wide --show-labels'
alias kgdepallowidesl='kubectl get deployment --all-namespaces -o=wide --show-labels'
alias kgstsallowidesl='kubectl get statefulset --all-namespaces -o=wide --show-labels'
alias kgsvcallowidesl='kubectl get service --all-namespaces -o=wide --show-labels'
alias kgingallowidesl='kubectl get ingress --all-namespaces -o=wide --show-labels'
alias kgcmallowidesl='kubectl get configmap --all-namespaces -o=wide --show-labels'
alias kgsecallowidesl='kubectl get secret --all-namespaces -o=wide --show-labels'
alias kgnsallowidesl='kubectl get namespaces --all-namespaces -o=wide --show-labels'
alias kgallslowide='kubectl get --all-namespaces --show-labels -o=wide'
alias kgpoallslowide='kubectl get pods --all-namespaces --show-labels -o=wide'
alias kgdepallslowide='kubectl get deployment --all-namespaces --show-labels -o=wide'
alias kgstsallslowide='kubectl get statefulset --all-namespaces --show-labels -o=wide'
alias kgsvcallslowide='kubectl get service --all-namespaces --show-labels -o=wide'
alias kgingallslowide='kubectl get ingress --all-namespaces --show-labels -o=wide'
alias kgcmallslowide='kubectl get configmap --all-namespaces --show-labels -o=wide'
alias kgsecallslowide='kubectl get secret --all-namespaces --show-labels -o=wide'
alias kgnsallslowide='kubectl get namespaces --all-namespaces --show-labels -o=wide'
alias kgslowideall='kubectl get --show-labels -o=wide --all-namespaces'
alias kgposlowideall='kubectl get pods --show-labels -o=wide --all-namespaces'
alias kgdepslowideall='kubectl get deployment --show-labels -o=wide --all-namespaces'
alias kgstsslowideall='kubectl get statefulset --show-labels -o=wide --all-namespaces'
alias kgsvcslowideall='kubectl get service --show-labels -o=wide --all-namespaces'
alias kgingslowideall='kubectl get ingress --show-labels -o=wide --all-namespaces'
alias kgcmslowideall='kubectl get configmap --show-labels -o=wide --all-namespaces'
alias kgsecslowideall='kubectl get secret --show-labels -o=wide --all-namespaces'
alias kgnsslowideall='kubectl get namespaces --show-labels -o=wide --all-namespaces'
alias kgslallowide='kubectl get --show-labels --all-namespaces -o=wide'
alias kgposlallowide='kubectl get pods --show-labels --all-namespaces -o=wide'
alias kgdepslallowide='kubectl get deployment --show-labels --all-namespaces -o=wide'
alias kgstsslallowide='kubectl get statefulset --show-labels --all-namespaces -o=wide'
alias kgsvcslallowide='kubectl get service --show-labels --all-namespaces -o=wide'
alias kgingslallowide='kubectl get ingress --show-labels --all-namespaces -o=wide'
alias kgcmslallowide='kubectl get configmap --show-labels --all-namespaces -o=wide'
alias kgsecslallowide='kubectl get secret --show-labels --all-namespaces -o=wide'
alias kgnsslallowide='kubectl get namespaces --show-labels --all-namespaces -o=wide'
alias kgallwowide='watch kubectl get --all-namespaces -o=wide'
alias kgpoallwowide='watch kubectl get pods --all-namespaces -o=wide'
alias kgdepallwowide='watch kubectl get deployment --all-namespaces -o=wide'
alias kgstsallwowide='watch kubectl get statefulset --all-namespaces -o=wide'
alias kgsvcallwowide='watch kubectl get service --all-namespaces -o=wide'
alias kgingallwowide='watch kubectl get ingress --all-namespaces -o=wide'
alias kgcmallwowide='watch kubectl get configmap --all-namespaces -o=wide'
alias kgsecallwowide='watch kubectl get secret --all-namespaces -o=wide'
alias kgnsallwowide='watch kubectl get namespaces --all-namespaces -o=wide'
alias kgwowideall='watch kubectl get -o=wide --all-namespaces'
alias kgpowowideall='watch kubectl get pods -o=wide --all-namespaces'
alias kgdepwowideall='watch kubectl get deployment -o=wide --all-namespaces'
alias kgstswowideall='watch kubectl get statefulset -o=wide --all-namespaces'
alias kgsvcwowideall='watch kubectl get service -o=wide --all-namespaces'
alias kgingwowideall='watch kubectl get ingress -o=wide --all-namespaces'
alias kgcmwowideall='watch kubectl get configmap -o=wide --all-namespaces'
alias kgsecwowideall='watch kubectl get secret -o=wide --all-namespaces'
alias kgnswowideall='watch kubectl get namespaces -o=wide --all-namespaces'
alias kgwallowide='watch kubectl get --all-namespaces -o=wide'
alias kgpowallowide='watch kubectl get pods --all-namespaces -o=wide'
alias kgdepwallowide='watch kubectl get deployment --all-namespaces -o=wide'
alias kgstswallowide='watch kubectl get statefulset --all-namespaces -o=wide'
alias kgsvcwallowide='watch kubectl get service --all-namespaces -o=wide'
alias kgingwallowide='watch kubectl get ingress --all-namespaces -o=wide'
alias kgcmwallowide='watch kubectl get configmap --all-namespaces -o=wide'
alias kgsecwallowide='watch kubectl get secret --all-namespaces -o=wide'
alias kgnswallowide='watch kubectl get namespaces --all-namespaces -o=wide'
alias kgslwowide='watch kubectl get --show-labels -o=wide'
alias ksysgslwowide='watch kubectl --namespace=kube-system get --show-labels -o=wide'
alias kgposlwowide='watch kubectl get pods --show-labels -o=wide'
alias ksysgposlwowide='watch kubectl --namespace=kube-system get pods --show-labels -o=wide'
alias kgdepslwowide='watch kubectl get deployment --show-labels -o=wide'
alias ksysgdepslwowide='watch kubectl --namespace=kube-system get deployment --show-labels -o=wide'
alias kgstsslwowide='watch kubectl get statefulset --show-labels -o=wide'
alias ksysgstsslwowide='watch kubectl --namespace=kube-system get statefulset --show-labels -o=wide'
alias kgsvcslwowide='watch kubectl get service --show-labels -o=wide'
alias ksysgsvcslwowide='watch kubectl --namespace=kube-system get service --show-labels -o=wide'
alias kgingslwowide='watch kubectl get ingress --show-labels -o=wide'
alias ksysgingslwowide='watch kubectl --namespace=kube-system get ingress --show-labels -o=wide'
alias kgcmslwowide='watch kubectl get configmap --show-labels -o=wide'
alias ksysgcmslwowide='watch kubectl --namespace=kube-system get configmap --show-labels -o=wide'
alias kgsecslwowide='watch kubectl get secret --show-labels -o=wide'
alias ksysgsecslwowide='watch kubectl --namespace=kube-system get secret --show-labels -o=wide'
alias kgnoslwowide='watch kubectl get nodes --show-labels -o=wide'
alias kgnsslwowide='watch kubectl get namespaces --show-labels -o=wide'
alias kgwowidesl='watch kubectl get -o=wide --show-labels'
alias ksysgwowidesl='watch kubectl --namespace=kube-system get -o=wide --show-labels'
alias kgpowowidesl='watch kubectl get pods -o=wide --show-labels'
alias ksysgpowowidesl='watch kubectl --namespace=kube-system get pods -o=wide --show-labels'
alias kgdepwowidesl='watch kubectl get deployment -o=wide --show-labels'
alias ksysgdepwowidesl='watch kubectl --namespace=kube-system get deployment -o=wide --show-labels'
alias kgstswowidesl='watch kubectl get statefulset -o=wide --show-labels'
alias ksysgstswowidesl='watch kubectl --namespace=kube-system get statefulset -o=wide --show-labels'
alias kgsvcwowidesl='watch kubectl get service -o=wide --show-labels'
alias ksysgsvcwowidesl='watch kubectl --namespace=kube-system get service -o=wide --show-labels'
alias kgingwowidesl='watch kubectl get ingress -o=wide --show-labels'
alias ksysgingwowidesl='watch kubectl --namespace=kube-system get ingress -o=wide --show-labels'
alias kgcmwowidesl='watch kubectl get configmap -o=wide --show-labels'
alias ksysgcmwowidesl='watch kubectl --namespace=kube-system get configmap -o=wide --show-labels'
alias kgsecwowidesl='watch kubectl get secret -o=wide --show-labels'
alias ksysgsecwowidesl='watch kubectl --namespace=kube-system get secret -o=wide --show-labels'
alias kgnowowidesl='watch kubectl get nodes -o=wide --show-labels'
alias kgnswowidesl='watch kubectl get namespaces -o=wide --show-labels'
alias kgwslowide='watch kubectl get --show-labels -o=wide'
alias ksysgwslowide='watch kubectl --namespace=kube-system get --show-labels -o=wide'
alias kgpowslowide='watch kubectl get pods --show-labels -o=wide'
alias ksysgpowslowide='watch kubectl --namespace=kube-system get pods --show-labels -o=wide'
alias kgdepwslowide='watch kubectl get deployment --show-labels -o=wide'
alias ksysgdepwslowide='watch kubectl --namespace=kube-system get deployment --show-labels -o=wide'
alias kgstswslowide='watch kubectl get statefulset --show-labels -o=wide'
alias ksysgstswslowide='watch kubectl --namespace=kube-system get statefulset --show-labels -o=wide'
alias kgsvcwslowide='watch kubectl get service --show-labels -o=wide'
alias ksysgsvcwslowide='watch kubectl --namespace=kube-system get service --show-labels -o=wide'
alias kgingwslowide='watch kubectl get ingress --show-labels -o=wide'
alias ksysgingwslowide='watch kubectl --namespace=kube-system get ingress --show-labels -o=wide'
alias kgcmwslowide='watch kubectl get configmap --show-labels -o=wide'
alias ksysgcmwslowide='watch kubectl --namespace=kube-system get configmap --show-labels -o=wide'
alias kgsecwslowide='watch kubectl get secret --show-labels -o=wide'
alias ksysgsecwslowide='watch kubectl --namespace=kube-system get secret --show-labels -o=wide'
alias kgnowslowide='watch kubectl get nodes --show-labels -o=wide'
alias kgnswslowide='watch kubectl get namespaces --show-labels -o=wide'
alias kgallwojson='watch kubectl get --all-namespaces -o=json'
alias kgpoallwojson='watch kubectl get pods --all-namespaces -o=json'
alias kgdepallwojson='watch kubectl get deployment --all-namespaces -o=json'
alias kgstsallwojson='watch kubectl get statefulset --all-namespaces -o=json'
alias kgsvcallwojson='watch kubectl get service --all-namespaces -o=json'
alias kgingallwojson='watch kubectl get ingress --all-namespaces -o=json'
alias kgcmallwojson='watch kubectl get configmap --all-namespaces -o=json'
alias kgsecallwojson='watch kubectl get secret --all-namespaces -o=json'
alias kgnsallwojson='watch kubectl get namespaces --all-namespaces -o=json'
alias kgwojsonall='watch kubectl get -o=json --all-namespaces'
alias kgpowojsonall='watch kubectl get pods -o=json --all-namespaces'
alias kgdepwojsonall='watch kubectl get deployment -o=json --all-namespaces'
alias kgstswojsonall='watch kubectl get statefulset -o=json --all-namespaces'
alias kgsvcwojsonall='watch kubectl get service -o=json --all-namespaces'
alias kgingwojsonall='watch kubectl get ingress -o=json --all-namespaces'
alias kgcmwojsonall='watch kubectl get configmap -o=json --all-namespaces'
alias kgsecwojsonall='watch kubectl get secret -o=json --all-namespaces'
alias kgnswojsonall='watch kubectl get namespaces -o=json --all-namespaces'
alias kgwallojson='watch kubectl get --all-namespaces -o=json'
alias kgpowallojson='watch kubectl get pods --all-namespaces -o=json'
alias kgdepwallojson='watch kubectl get deployment --all-namespaces -o=json'
alias kgstswallojson='watch kubectl get statefulset --all-namespaces -o=json'
alias kgsvcwallojson='watch kubectl get service --all-namespaces -o=json'
alias kgingwallojson='watch kubectl get ingress --all-namespaces -o=json'
alias kgcmwallojson='watch kubectl get configmap --all-namespaces -o=json'
alias kgsecwallojson='watch kubectl get secret --all-namespaces -o=json'
alias kgnswallojson='watch kubectl get namespaces --all-namespaces -o=json'
alias kgallslw='watch kubectl get --all-namespaces --show-labels'
alias kgpoallslw='watch kubectl get pods --all-namespaces --show-labels'
alias kgdepallslw='watch kubectl get deployment --all-namespaces --show-labels'
alias kgstsallslw='watch kubectl get statefulset --all-namespaces --show-labels'
alias kgsvcallslw='watch kubectl get service --all-namespaces --show-labels'
alias kgingallslw='watch kubectl get ingress --all-namespaces --show-labels'
alias kgcmallslw='watch kubectl get configmap --all-namespaces --show-labels'
alias kgsecallslw='watch kubectl get secret --all-namespaces --show-labels'
alias kgnsallslw='watch kubectl get namespaces --all-namespaces --show-labels'
alias kgallwsl='watch kubectl get --all-namespaces --show-labels'
alias kgpoallwsl='watch kubectl get pods --all-namespaces --show-labels'
alias kgdepallwsl='watch kubectl get deployment --all-namespaces --show-labels'
alias kgstsallwsl='watch kubectl get statefulset --all-namespaces --show-labels'
alias kgsvcallwsl='watch kubectl get service --all-namespaces --show-labels'
alias kgingallwsl='watch kubectl get ingress --all-namespaces --show-labels'
alias kgcmallwsl='watch kubectl get configmap --all-namespaces --show-labels'
alias kgsecallwsl='watch kubectl get secret --all-namespaces --show-labels'
alias kgnsallwsl='watch kubectl get namespaces --all-namespaces --show-labels'
alias kgslallw='watch kubectl get --show-labels --all-namespaces'
alias kgposlallw='watch kubectl get pods --show-labels --all-namespaces'
alias kgdepslallw='watch kubectl get deployment --show-labels --all-namespaces'
alias kgstsslallw='watch kubectl get statefulset --show-labels --all-namespaces'
alias kgsvcslallw='watch kubectl get service --show-labels --all-namespaces'
alias kgingslallw='watch kubectl get ingress --show-labels --all-namespaces'
alias kgcmslallw='watch kubectl get configmap --show-labels --all-namespaces'
alias kgsecslallw='watch kubectl get secret --show-labels --all-namespaces'
alias kgnsslallw='watch kubectl get namespaces --show-labels --all-namespaces'
alias kgslwall='watch kubectl get --show-labels --all-namespaces'
alias kgposlwall='watch kubectl get pods --show-labels --all-namespaces'
alias kgdepslwall='watch kubectl get deployment --show-labels --all-namespaces'
alias kgstsslwall='watch kubectl get statefulset --show-labels --all-namespaces'
alias kgsvcslwall='watch kubectl get service --show-labels --all-namespaces'
alias kgingslwall='watch kubectl get ingress --show-labels --all-namespaces'
alias kgcmslwall='watch kubectl get configmap --show-labels --all-namespaces'
alias kgsecslwall='watch kubectl get secret --show-labels --all-namespaces'
alias kgnsslwall='watch kubectl get namespaces --show-labels --all-namespaces'
alias kgwallsl='watch kubectl get --all-namespaces --show-labels'
alias kgpowallsl='watch kubectl get pods --all-namespaces --show-labels'
alias kgdepwallsl='watch kubectl get deployment --all-namespaces --show-labels'
alias kgstswallsl='watch kubectl get statefulset --all-namespaces --show-labels'
alias kgsvcwallsl='watch kubectl get service --all-namespaces --show-labels'
alias kgingwallsl='watch kubectl get ingress --all-namespaces --show-labels'
alias kgcmwallsl='watch kubectl get configmap --all-namespaces --show-labels'
alias kgsecwallsl='watch kubectl get secret --all-namespaces --show-labels'
alias kgnswallsl='watch kubectl get namespaces --all-namespaces --show-labels'
alias kgwslall='watch kubectl get --show-labels --all-namespaces'
alias kgpowslall='watch kubectl get pods --show-labels --all-namespaces'
alias kgdepwslall='watch kubectl get deployment --show-labels --all-namespaces'
alias kgstswslall='watch kubectl get statefulset --show-labels --all-namespaces'
alias kgsvcwslall='watch kubectl get service --show-labels --all-namespaces'
alias kgingwslall='watch kubectl get ingress --show-labels --all-namespaces'
alias kgcmwslall='watch kubectl get configmap --show-labels --all-namespaces'
alias kgsecwslall='watch kubectl get secret --show-labels --all-namespaces'
alias kgnswslall='watch kubectl get namespaces --show-labels --all-namespaces'
alias kgallslwowide='watch kubectl get --all-namespaces --show-labels -o=wide'
alias kgpoallslwowide='watch kubectl get pods --all-namespaces --show-labels -o=wide'
alias kgdepallslwowide='watch kubectl get deployment --all-namespaces --show-labels -o=wide'
alias kgstsallslwowide='watch kubectl get statefulset --all-namespaces --show-labels -o=wide'
alias kgsvcallslwowide='watch kubectl get service --all-namespaces --show-labels -o=wide'
alias kgingallslwowide='watch kubectl get ingress --all-namespaces --show-labels -o=wide'
alias kgcmallslwowide='watch kubectl get configmap --all-namespaces --show-labels -o=wide'
alias kgsecallslwowide='watch kubectl get secret --all-namespaces --show-labels -o=wide'
alias kgnsallslwowide='watch kubectl get namespaces --all-namespaces --show-labels -o=wide'
alias kgallwowidesl='watch kubectl get --all-namespaces -o=wide --show-labels'
alias kgpoallwowidesl='watch kubectl get pods --all-namespaces -o=wide --show-labels'
alias kgdepallwowidesl='watch kubectl get deployment --all-namespaces -o=wide --show-labels'
alias kgstsallwowidesl='watch kubectl get statefulset --all-namespaces -o=wide --show-labels'
alias kgsvcallwowidesl='watch kubectl get service --all-namespaces -o=wide --show-labels'
alias kgingallwowidesl='watch kubectl get ingress --all-namespaces -o=wide --show-labels'
alias kgcmallwowidesl='watch kubectl get configmap --all-namespaces -o=wide --show-labels'
alias kgsecallwowidesl='watch kubectl get secret --all-namespaces -o=wide --show-labels'
alias kgnsallwowidesl='watch kubectl get namespaces --all-namespaces -o=wide --show-labels'
alias kgallwslowide='watch kubectl get --all-namespaces --show-labels -o=wide'
alias kgpoallwslowide='watch kubectl get pods --all-namespaces --show-labels -o=wide'
alias kgdepallwslowide='watch kubectl get deployment --all-namespaces --show-labels -o=wide'
alias kgstsallwslowide='watch kubectl get statefulset --all-namespaces --show-labels -o=wide'
alias kgsvcallwslowide='watch kubectl get service --all-namespaces --show-labels -o=wide'
alias kgingallwslowide='watch kubectl get ingress --all-namespaces --show-labels -o=wide'
alias kgcmallwslowide='watch kubectl get configmap --all-namespaces --show-labels -o=wide'
alias kgsecallwslowide='watch kubectl get secret --all-namespaces --show-labels -o=wide'
alias kgnsallwslowide='watch kubectl get namespaces --all-namespaces --show-labels -o=wide'
alias kgslallwowide='watch kubectl get --show-labels --all-namespaces -o=wide'
alias kgposlallwowide='watch kubectl get pods --show-labels --all-namespaces -o=wide'
alias kgdepslallwowide='watch kubectl get deployment --show-labels --all-namespaces -o=wide'
alias kgstsslallwowide='watch kubectl get statefulset --show-labels --all-namespaces -o=wide'
alias kgsvcslallwowide='watch kubectl get service --show-labels --all-namespaces -o=wide'
alias kgingslallwowide='watch kubectl get ingress --show-labels --all-namespaces -o=wide'
alias kgcmslallwowide='watch kubectl get configmap --show-labels --all-namespaces -o=wide'
alias kgsecslallwowide='watch kubectl get secret --show-labels --all-namespaces -o=wide'
alias kgnsslallwowide='watch kubectl get namespaces --show-labels --all-namespaces -o=wide'
alias kgslwowideall='watch kubectl get --show-labels -o=wide --all-namespaces'
alias kgposlwowideall='watch kubectl get pods --show-labels -o=wide --all-namespaces'
alias kgdepslwowideall='watch kubectl get deployment --show-labels -o=wide --all-namespaces'
alias kgstsslwowideall='watch kubectl get statefulset --show-labels -o=wide --all-namespaces'
alias kgsvcslwowideall='watch kubectl get service --show-labels -o=wide --all-namespaces'
alias kgingslwowideall='watch kubectl get ingress --show-labels -o=wide --all-namespaces'
alias kgcmslwowideall='watch kubectl get configmap --show-labels -o=wide --all-namespaces'
alias kgsecslwowideall='watch kubectl get secret --show-labels -o=wide --all-namespaces'
alias kgnsslwowideall='watch kubectl get namespaces --show-labels -o=wide --all-namespaces'
alias kgslwallowide='watch kubectl get --show-labels --all-namespaces -o=wide'
alias kgposlwallowide='watch kubectl get pods --show-labels --all-namespaces -o=wide'
alias kgdepslwallowide='watch kubectl get deployment --show-labels --all-namespaces -o=wide'
alias kgstsslwallowide='watch kubectl get statefulset --show-labels --all-namespaces -o=wide'
alias kgsvcslwallowide='watch kubectl get service --show-labels --all-namespaces -o=wide'
alias kgingslwallowide='watch kubectl get ingress --show-labels --all-namespaces -o=wide'
alias kgcmslwallowide='watch kubectl get configmap --show-labels --all-namespaces -o=wide'
alias kgsecslwallowide='watch kubectl get secret --show-labels --all-namespaces -o=wide'
alias kgnsslwallowide='watch kubectl get namespaces --show-labels --all-namespaces -o=wide'
alias kgwowideallsl='watch kubectl get -o=wide --all-namespaces --show-labels'
alias kgpowowideallsl='watch kubectl get pods -o=wide --all-namespaces --show-labels'
alias kgdepwowideallsl='watch kubectl get deployment -o=wide --all-namespaces --show-labels'
alias kgstswowideallsl='watch kubectl get statefulset -o=wide --all-namespaces --show-labels'
alias kgsvcwowideallsl='watch kubectl get service -o=wide --all-namespaces --show-labels'
alias kgingwowideallsl='watch kubectl get ingress -o=wide --all-namespaces --show-labels'
alias kgcmwowideallsl='watch kubectl get configmap -o=wide --all-namespaces --show-labels'
alias kgsecwowideallsl='watch kubectl get secret -o=wide --all-namespaces --show-labels'
alias kgnswowideallsl='watch kubectl get namespaces -o=wide --all-namespaces --show-labels'
alias kgwowideslall='watch kubectl get -o=wide --show-labels --all-namespaces'
alias kgpowowideslall='watch kubectl get pods -o=wide --show-labels --all-namespaces'
alias kgdepwowideslall='watch kubectl get deployment -o=wide --show-labels --all-namespaces'
alias kgstswowideslall='watch kubectl get statefulset -o=wide --show-labels --all-namespaces'
alias kgsvcwowideslall='watch kubectl get service -o=wide --show-labels --all-namespaces'
alias kgingwowideslall='watch kubectl get ingress -o=wide --show-labels --all-namespaces'
alias kgcmwowideslall='watch kubectl get configmap -o=wide --show-labels --all-namespaces'
alias kgsecwowideslall='watch kubectl get secret -o=wide --show-labels --all-namespaces'
alias kgnswowideslall='watch kubectl get namespaces -o=wide --show-labels --all-namespaces'
alias kgwallowidesl='watch kubectl get --all-namespaces -o=wide --show-labels'
alias kgpowallowidesl='watch kubectl get pods --all-namespaces -o=wide --show-labels'
alias kgdepwallowidesl='watch kubectl get deployment --all-namespaces -o=wide --show-labels'
alias kgstswallowidesl='watch kubectl get statefulset --all-namespaces -o=wide --show-labels'
alias kgsvcwallowidesl='watch kubectl get service --all-namespaces -o=wide --show-labels'
alias kgingwallowidesl='watch kubectl get ingress --all-namespaces -o=wide --show-labels'
alias kgcmwallowidesl='watch kubectl get configmap --all-namespaces -o=wide --show-labels'
alias kgsecwallowidesl='watch kubectl get secret --all-namespaces -o=wide --show-labels'
alias kgnswallowidesl='watch kubectl get namespaces --all-namespaces -o=wide --show-labels'
alias kgwallslowide='watch kubectl get --all-namespaces --show-labels -o=wide'
alias kgpowallslowide='watch kubectl get pods --all-namespaces --show-labels -o=wide'
alias kgdepwallslowide='watch kubectl get deployment --all-namespaces --show-labels -o=wide'
alias kgstswallslowide='watch kubectl get statefulset --all-namespaces --show-labels -o=wide'
alias kgsvcwallslowide='watch kubectl get service --all-namespaces --show-labels -o=wide'
alias kgingwallslowide='watch kubectl get ingress --all-namespaces --show-labels -o=wide'
alias kgcmwallslowide='watch kubectl get configmap --all-namespaces --show-labels -o=wide'
alias kgsecwallslowide='watch kubectl get secret --all-namespaces --show-labels -o=wide'
alias kgnswallslowide='watch kubectl get namespaces --all-namespaces --show-labels -o=wide'
alias kgwslowideall='watch kubectl get --show-labels -o=wide --all-namespaces'
alias kgpowslowideall='watch kubectl get pods --show-labels -o=wide --all-namespaces'
alias kgdepwslowideall='watch kubectl get deployment --show-labels -o=wide --all-namespaces'
alias kgstswslowideall='watch kubectl get statefulset --show-labels -o=wide --all-namespaces'
alias kgsvcwslowideall='watch kubectl get service --show-labels -o=wide --all-namespaces'
alias kgingwslowideall='watch kubectl get ingress --show-labels -o=wide --all-namespaces'
alias kgcmwslowideall='watch kubectl get configmap --show-labels -o=wide --all-namespaces'
alias kgsecwslowideall='watch kubectl get secret --show-labels -o=wide --all-namespaces'
alias kgnswslowideall='watch kubectl get namespaces --show-labels -o=wide --all-namespaces'
alias kgwslallowide='watch kubectl get --show-labels --all-namespaces -o=wide'
alias kgpowslallowide='watch kubectl get pods --show-labels --all-namespaces -o=wide'
alias kgdepwslallowide='watch kubectl get deployment --show-labels --all-namespaces -o=wide'
alias kgstswslallowide='watch kubectl get statefulset --show-labels --all-namespaces -o=wide'
alias kgsvcwslallowide='watch kubectl get service --show-labels --all-namespaces -o=wide'
alias kgingwslallowide='watch kubectl get ingress --show-labels --all-namespaces -o=wide'
alias kgcmwslallowide='watch kubectl get configmap --show-labels --all-namespaces -o=wide'
alias kgsecwslallowide='watch kubectl get secret --show-labels --all-namespaces -o=wide'
alias kgnswslallowide='watch kubectl get namespaces --show-labels --all-namespaces -o=wide'
alias kgf='kubectl get --recursive -f'
alias kdf='kubectl describe --recursive -f'
alias krmf='kubectl delete --recursive -f'
alias kgoyamlf='kubectl get -o=yaml --recursive -f'
alias kgowidef='kubectl get -o=wide --recursive -f'
alias kgojsonf='kubectl get -o=json --recursive -f'
alias kgslf='kubectl get --show-labels --recursive -f'
alias kgwf='watch kubectl get --recursive -f'
alias kgwoyamlf='watch kubectl get -o=yaml --recursive -f'
alias kgowideslf='kubectl get -o=wide --show-labels --recursive -f'
alias kgslowidef='kubectl get --show-labels -o=wide --recursive -f'
alias kgwowidef='watch kubectl get -o=wide --recursive -f'
alias kgwojsonf='watch kubectl get -o=json --recursive -f'
alias kgslwf='watch kubectl get --show-labels --recursive -f'
alias kgwslf='watch kubectl get --show-labels --recursive -f'
alias kgslwowidef='watch kubectl get --show-labels -o=wide --recursive -f'
alias kgwowideslf='watch kubectl get -o=wide --show-labels --recursive -f'
alias kgwslowidef='watch kubectl get --show-labels -o=wide --recursive -f'
alias kgl='kubectl get -l'
alias ksysgl='kubectl --namespace=kube-system get -l'
alias kdl='kubectl describe -l'
alias ksysdl='kubectl --namespace=kube-system describe -l'
alias krml='kubectl delete -l'
alias ksysrml='kubectl --namespace=kube-system delete -l'
alias kgpol='kubectl get pods -l'
alias ksysgpol='kubectl --namespace=kube-system get pods -l'
alias kdpol='kubectl describe pods -l'
alias ksysdpol='kubectl --namespace=kube-system describe pods -l'
alias krmpol='kubectl delete pods -l'
alias ksysrmpol='kubectl --namespace=kube-system delete pods -l'
alias kgdepl='kubectl get deployment -l'
alias ksysgdepl='kubectl --namespace=kube-system get deployment -l'
alias kddepl='kubectl describe deployment -l'
alias ksysddepl='kubectl --namespace=kube-system describe deployment -l'
alias krmdepl='kubectl delete deployment -l'
alias ksysrmdepl='kubectl --namespace=kube-system delete deployment -l'
alias kgstsl='kubectl get statefulset -l'
alias ksysgstsl='kubectl --namespace=kube-system get statefulset -l'
alias kdstsl='kubectl describe statefulset -l'
alias ksysdstsl='kubectl --namespace=kube-system describe statefulset -l'
alias krmstsl='kubectl delete statefulset -l'
alias ksysrmstsl='kubectl --namespace=kube-system delete statefulset -l'
alias kgsvcl='kubectl get service -l'
alias ksysgsvcl='kubectl --namespace=kube-system get service -l'
alias kdsvcl='kubectl describe service -l'
alias ksysdsvcl='kubectl --namespace=kube-system describe service -l'
alias krmsvcl='kubectl delete service -l'
alias ksysrmsvcl='kubectl --namespace=kube-system delete service -l'
alias kgingl='kubectl get ingress -l'
alias ksysgingl='kubectl --namespace=kube-system get ingress -l'
alias kdingl='kubectl describe ingress -l'
alias ksysdingl='kubectl --namespace=kube-system describe ingress -l'
alias krmingl='kubectl delete ingress -l'
alias ksysrmingl='kubectl --namespace=kube-system delete ingress -l'
alias kgcml='kubectl get configmap -l'
alias ksysgcml='kubectl --namespace=kube-system get configmap -l'
alias kdcml='kubectl describe configmap -l'
alias ksysdcml='kubectl --namespace=kube-system describe configmap -l'
alias krmcml='kubectl delete configmap -l'
alias ksysrmcml='kubectl --namespace=kube-system delete configmap -l'
alias kgsecl='kubectl get secret -l'
alias ksysgsecl='kubectl --namespace=kube-system get secret -l'
alias kdsecl='kubectl describe secret -l'
alias ksysdsecl='kubectl --namespace=kube-system describe secret -l'
alias krmsecl='kubectl delete secret -l'
alias ksysrmsecl='kubectl --namespace=kube-system delete secret -l'
alias kgnol='kubectl get nodes -l'
alias kdnol='kubectl describe nodes -l'
alias kgnsl='kubectl get namespaces -l'
alias kdnsl='kubectl describe namespaces -l'
alias krmnsl='kubectl delete namespaces -l'
alias kgoyamll='kubectl get -o=yaml -l'
alias ksysgoyamll='kubectl --namespace=kube-system get -o=yaml -l'
alias kgpooyamll='kubectl get pods -o=yaml -l'
alias ksysgpooyamll='kubectl --namespace=kube-system get pods -o=yaml -l'
alias kgdepoyamll='kubectl get deployment -o=yaml -l'
alias ksysgdepoyamll='kubectl --namespace=kube-system get deployment -o=yaml -l'
alias kgstsoyamll='kubectl get statefulset -o=yaml -l'
alias ksysgstsoyamll='kubectl --namespace=kube-system get statefulset -o=yaml -l'
alias kgsvcoyamll='kubectl get service -o=yaml -l'
alias ksysgsvcoyamll='kubectl --namespace=kube-system get service -o=yaml -l'
alias kgingoyamll='kubectl get ingress -o=yaml -l'
alias ksysgingoyamll='kubectl --namespace=kube-system get ingress -o=yaml -l'
alias kgcmoyamll='kubectl get configmap -o=yaml -l'
alias ksysgcmoyamll='kubectl --namespace=kube-system get configmap -o=yaml -l'
alias kgsecoyamll='kubectl get secret -o=yaml -l'
alias ksysgsecoyamll='kubectl --namespace=kube-system get secret -o=yaml -l'
alias kgnooyamll='kubectl get nodes -o=yaml -l'
alias kgnsoyamll='kubectl get namespaces -o=yaml -l'
alias kgowidel='kubectl get -o=wide -l'
alias ksysgowidel='kubectl --namespace=kube-system get -o=wide -l'
alias kgpoowidel='kubectl get pods -o=wide -l'
alias ksysgpoowidel='kubectl --namespace=kube-system get pods -o=wide -l'
alias kgdepowidel='kubectl get deployment -o=wide -l'
alias ksysgdepowidel='kubectl --namespace=kube-system get deployment -o=wide -l'
alias kgstsowidel='kubectl get statefulset -o=wide -l'
alias ksysgstsowidel='kubectl --namespace=kube-system get statefulset -o=wide -l'
alias kgsvcowidel='kubectl get service -o=wide -l'
alias ksysgsvcowidel='kubectl --namespace=kube-system get service -o=wide -l'
alias kgingowidel='kubectl get ingress -o=wide -l'
alias ksysgingowidel='kubectl --namespace=kube-system get ingress -o=wide -l'
alias kgcmowidel='kubectl get configmap -o=wide -l'
alias ksysgcmowidel='kubectl --namespace=kube-system get configmap -o=wide -l'
alias kgsecowidel='kubectl get secret -o=wide -l'
alias ksysgsecowidel='kubectl --namespace=kube-system get secret -o=wide -l'
alias kgnoowidel='kubectl get nodes -o=wide -l'
alias kgnsowidel='kubectl get namespaces -o=wide -l'
alias kgojsonl='kubectl get -o=json -l'
alias ksysgojsonl='kubectl --namespace=kube-system get -o=json -l'
alias kgpoojsonl='kubectl get pods -o=json -l'
alias ksysgpoojsonl='kubectl --namespace=kube-system get pods -o=json -l'
alias kgdepojsonl='kubectl get deployment -o=json -l'
alias ksysgdepojsonl='kubectl --namespace=kube-system get deployment -o=json -l'
alias kgstsojsonl='kubectl get statefulset -o=json -l'
alias ksysgstsojsonl='kubectl --namespace=kube-system get statefulset -o=json -l'
alias kgsvcojsonl='kubectl get service -o=json -l'
alias ksysgsvcojsonl='kubectl --namespace=kube-system get service -o=json -l'
alias kgingojsonl='kubectl get ingress -o=json -l'
alias ksysgingojsonl='kubectl --namespace=kube-system get ingress -o=json -l'
alias kgcmojsonl='kubectl get configmap -o=json -l'
alias ksysgcmojsonl='kubectl --namespace=kube-system get configmap -o=json -l'
alias kgsecojsonl='kubectl get secret -o=json -l'
alias ksysgsecojsonl='kubectl --namespace=kube-system get secret -o=json -l'
alias kgnoojsonl='kubectl get nodes -o=json -l'
alias kgnsojsonl='kubectl get namespaces -o=json -l'
alias kgsll='kubectl get --show-labels -l'
alias ksysgsll='kubectl --namespace=kube-system get --show-labels -l'
alias kgposll='kubectl get pods --show-labels -l'
alias ksysgposll='kubectl --namespace=kube-system get pods --show-labels -l'
alias kgdepsll='kubectl get deployment --show-labels -l'
alias ksysgdepsll='kubectl --namespace=kube-system get deployment --show-labels -l'
alias kgstssll='kubectl get statefulset --show-labels -l'
alias ksysgstssll='kubectl --namespace=kube-system get statefulset --show-labels -l'
alias kgsvcsll='kubectl get service --show-labels -l'
alias ksysgsvcsll='kubectl --namespace=kube-system get service --show-labels -l'
alias kgingsll='kubectl get ingress --show-labels -l'
alias ksysgingsll='kubectl --namespace=kube-system get ingress --show-labels -l'
alias kgcmsll='kubectl get configmap --show-labels -l'
alias ksysgcmsll='kubectl --namespace=kube-system get configmap --show-labels -l'
alias kgsecsll='kubectl get secret --show-labels -l'
alias ksysgsecsll='kubectl --namespace=kube-system get secret --show-labels -l'
alias kgnosll='kubectl get nodes --show-labels -l'
alias kgnssll='kubectl get namespaces --show-labels -l'
alias kgwl='watch kubectl get -l'
alias ksysgwl='watch kubectl --namespace=kube-system get -l'
alias kgpowl='watch kubectl get pods -l'
alias ksysgpowl='watch kubectl --namespace=kube-system get pods -l'
alias kgdepwl='watch kubectl get deployment -l'
alias ksysgdepwl='watch kubectl --namespace=kube-system get deployment -l'
alias kgstswl='watch kubectl get statefulset -l'
alias ksysgstswl='watch kubectl --namespace=kube-system get statefulset -l'
alias kgsvcwl='watch kubectl get service -l'
alias ksysgsvcwl='watch kubectl --namespace=kube-system get service -l'
alias kgingwl='watch kubectl get ingress -l'
alias ksysgingwl='watch kubectl --namespace=kube-system get ingress -l'
alias kgcmwl='watch kubectl get configmap -l'
alias ksysgcmwl='watch kubectl --namespace=kube-system get configmap -l'
alias kgsecwl='watch kubectl get secret -l'
alias ksysgsecwl='watch kubectl --namespace=kube-system get secret -l'
alias kgnowl='watch kubectl get nodes -l'
alias kgnswl='watch kubectl get namespaces -l'
alias kgwoyamll='watch kubectl get -o=yaml -l'
alias ksysgwoyamll='watch kubectl --namespace=kube-system get -o=yaml -l'
alias kgpowoyamll='watch kubectl get pods -o=yaml -l'
alias ksysgpowoyamll='watch kubectl --namespace=kube-system get pods -o=yaml -l'
alias kgdepwoyamll='watch kubectl get deployment -o=yaml -l'
alias ksysgdepwoyamll='watch kubectl --namespace=kube-system get deployment -o=yaml -l'
alias kgstswoyamll='watch kubectl get statefulset -o=yaml -l'
alias ksysgstswoyamll='watch kubectl --namespace=kube-system get statefulset -o=yaml -l'
alias kgsvcwoyamll='watch kubectl get service -o=yaml -l'
alias ksysgsvcwoyamll='watch kubectl --namespace=kube-system get service -o=yaml -l'
alias kgingwoyamll='watch kubectl get ingress -o=yaml -l'
alias ksysgingwoyamll='watch kubectl --namespace=kube-system get ingress -o=yaml -l'
alias kgcmwoyamll='watch kubectl get configmap -o=yaml -l'
alias ksysgcmwoyamll='watch kubectl --namespace=kube-system get configmap -o=yaml -l'
alias kgsecwoyamll='watch kubectl get secret -o=yaml -l'
alias ksysgsecwoyamll='watch kubectl --namespace=kube-system get secret -o=yaml -l'
alias kgnowoyamll='watch kubectl get nodes -o=yaml -l'
alias kgnswoyamll='watch kubectl get namespaces -o=yaml -l'
alias kgowidesll='kubectl get -o=wide --show-labels -l'
alias ksysgowidesll='kubectl --namespace=kube-system get -o=wide --show-labels -l'
alias kgpoowidesll='kubectl get pods -o=wide --show-labels -l'
alias ksysgpoowidesll='kubectl --namespace=kube-system get pods -o=wide --show-labels -l'
alias kgdepowidesll='kubectl get deployment -o=wide --show-labels -l'
alias ksysgdepowidesll='kubectl --namespace=kube-system get deployment -o=wide --show-labels -l'
alias kgstsowidesll='kubectl get statefulset -o=wide --show-labels -l'
alias ksysgstsowidesll='kubectl --namespace=kube-system get statefulset -o=wide --show-labels -l'
alias kgsvcowidesll='kubectl get service -o=wide --show-labels -l'
alias ksysgsvcowidesll='kubectl --namespace=kube-system get service -o=wide --show-labels -l'
alias kgingowidesll='kubectl get ingress -o=wide --show-labels -l'
alias ksysgingowidesll='kubectl --namespace=kube-system get ingress -o=wide --show-labels -l'
alias kgcmowidesll='kubectl get configmap -o=wide --show-labels -l'
alias ksysgcmowidesll='kubectl --namespace=kube-system get configmap -o=wide --show-labels -l'
alias kgsecowidesll='kubectl get secret -o=wide --show-labels -l'
alias ksysgsecowidesll='kubectl --namespace=kube-system get secret -o=wide --show-labels -l'
alias kgnoowidesll='kubectl get nodes -o=wide --show-labels -l'
alias kgnsowidesll='kubectl get namespaces -o=wide --show-labels -l'
alias kgslowidel='kubectl get --show-labels -o=wide -l'
alias ksysgslowidel='kubectl --namespace=kube-system get --show-labels -o=wide -l'
alias kgposlowidel='kubectl get pods --show-labels -o=wide -l'
alias ksysgposlowidel='kubectl --namespace=kube-system get pods --show-labels -o=wide -l'
alias kgdepslowidel='kubectl get deployment --show-labels -o=wide -l'
alias ksysgdepslowidel='kubectl --namespace=kube-system get deployment --show-labels -o=wide -l'
alias kgstsslowidel='kubectl get statefulset --show-labels -o=wide -l'
alias ksysgstsslowidel='kubectl --namespace=kube-system get statefulset --show-labels -o=wide -l'
alias kgsvcslowidel='kubectl get service --show-labels -o=wide -l'
alias ksysgsvcslowidel='kubectl --namespace=kube-system get service --show-labels -o=wide -l'
alias kgingslowidel='kubectl get ingress --show-labels -o=wide -l'
alias ksysgingslowidel='kubectl --namespace=kube-system get ingress --show-labels -o=wide -l'
alias kgcmslowidel='kubectl get configmap --show-labels -o=wide -l'
alias ksysgcmslowidel='kubectl --namespace=kube-system get configmap --show-labels -o=wide -l'
alias kgsecslowidel='kubectl get secret --show-labels -o=wide -l'
alias ksysgsecslowidel='kubectl --namespace=kube-system get secret --show-labels -o=wide -l'
alias kgnoslowidel='kubectl get nodes --show-labels -o=wide -l'
alias kgnsslowidel='kubectl get namespaces --show-labels -o=wide -l'
alias kgwowidel='watch kubectl get -o=wide -l'
alias ksysgwowidel='watch kubectl --namespace=kube-system get -o=wide -l'
alias kgpowowidel='watch kubectl get pods -o=wide -l'
alias ksysgpowowidel='watch kubectl --namespace=kube-system get pods -o=wide -l'
alias kgdepwowidel='watch kubectl get deployment -o=wide -l'
alias ksysgdepwowidel='watch kubectl --namespace=kube-system get deployment -o=wide -l'
alias kgstswowidel='watch kubectl get statefulset -o=wide -l'
alias ksysgstswowidel='watch kubectl --namespace=kube-system get statefulset -o=wide -l'
alias kgsvcwowidel='watch kubectl get service -o=wide -l'
alias ksysgsvcwowidel='watch kubectl --namespace=kube-system get service -o=wide -l'
alias kgingwowidel='watch kubectl get ingress -o=wide -l'
alias ksysgingwowidel='watch kubectl --namespace=kube-system get ingress -o=wide -l'
alias kgcmwowidel='watch kubectl get configmap -o=wide -l'
alias ksysgcmwowidel='watch kubectl --namespace=kube-system get configmap -o=wide -l'
alias kgsecwowidel='watch kubectl get secret -o=wide -l'
alias ksysgsecwowidel='watch kubectl --namespace=kube-system get secret -o=wide -l'
alias kgnowowidel='watch kubectl get nodes -o=wide -l'
alias kgnswowidel='watch kubectl get namespaces -o=wide -l'
alias kgwojsonl='watch kubectl get -o=json -l'
alias ksysgwojsonl='watch kubectl --namespace=kube-system get -o=json -l'
alias kgpowojsonl='watch kubectl get pods -o=json -l'
alias ksysgpowojsonl='watch kubectl --namespace=kube-system get pods -o=json -l'
alias kgdepwojsonl='watch kubectl get deployment -o=json -l'
alias ksysgdepwojsonl='watch kubectl --namespace=kube-system get deployment -o=json -l'
alias kgstswojsonl='watch kubectl get statefulset -o=json -l'
alias ksysgstswojsonl='watch kubectl --namespace=kube-system get statefulset -o=json -l'
alias kgsvcwojsonl='watch kubectl get service -o=json -l'
alias ksysgsvcwojsonl='watch kubectl --namespace=kube-system get service -o=json -l'
alias kgingwojsonl='watch kubectl get ingress -o=json -l'
alias ksysgingwojsonl='watch kubectl --namespace=kube-system get ingress -o=json -l'
alias kgcmwojsonl='watch kubectl get configmap -o=json -l'
alias ksysgcmwojsonl='watch kubectl --namespace=kube-system get configmap -o=json -l'
alias kgsecwojsonl='watch kubectl get secret -o=json -l'
alias ksysgsecwojsonl='watch kubectl --namespace=kube-system get secret -o=json -l'
alias kgnowojsonl='watch kubectl get nodes -o=json -l'
alias kgnswojsonl='watch kubectl get namespaces -o=json -l'
alias kgslwl='watch kubectl get --show-labels -l'
alias ksysgslwl='watch kubectl --namespace=kube-system get --show-labels -l'
alias kgposlwl='watch kubectl get pods --show-labels -l'
alias ksysgposlwl='watch kubectl --namespace=kube-system get pods --show-labels -l'
alias kgdepslwl='watch kubectl get deployment --show-labels -l'
alias ksysgdepslwl='watch kubectl --namespace=kube-system get deployment --show-labels -l'
alias kgstsslwl='watch kubectl get statefulset --show-labels -l'
alias ksysgstsslwl='watch kubectl --namespace=kube-system get statefulset --show-labels -l'
alias kgsvcslwl='watch kubectl get service --show-labels -l'
alias ksysgsvcslwl='watch kubectl --namespace=kube-system get service --show-labels -l'
alias kgingslwl='watch kubectl get ingress --show-labels -l'
alias ksysgingslwl='watch kubectl --namespace=kube-system get ingress --show-labels -l'
alias kgcmslwl='watch kubectl get configmap --show-labels -l'
alias ksysgcmslwl='watch kubectl --namespace=kube-system get configmap --show-labels -l'
alias kgsecslwl='watch kubectl get secret --show-labels -l'
alias ksysgsecslwl='watch kubectl --namespace=kube-system get secret --show-labels -l'
alias kgnoslwl='watch kubectl get nodes --show-labels -l'
alias kgnsslwl='watch kubectl get namespaces --show-labels -l'
alias kgwsll='watch kubectl get --show-labels -l'
alias ksysgwsll='watch kubectl --namespace=kube-system get --show-labels -l'
alias kgpowsll='watch kubectl get pods --show-labels -l'
alias ksysgpowsll='watch kubectl --namespace=kube-system get pods --show-labels -l'
alias kgdepwsll='watch kubectl get deployment --show-labels -l'
alias ksysgdepwsll='watch kubectl --namespace=kube-system get deployment --show-labels -l'
alias kgstswsll='watch kubectl get statefulset --show-labels -l'
alias ksysgstswsll='watch kubectl --namespace=kube-system get statefulset --show-labels -l'
alias kgsvcwsll='watch kubectl get service --show-labels -l'
alias ksysgsvcwsll='watch kubectl --namespace=kube-system get service --show-labels -l'
alias kgingwsll='watch kubectl get ingress --show-labels -l'
alias ksysgingwsll='watch kubectl --namespace=kube-system get ingress --show-labels -l'
alias kgcmwsll='watch kubectl get configmap --show-labels -l'
alias ksysgcmwsll='watch kubectl --namespace=kube-system get configmap --show-labels -l'
alias kgsecwsll='watch kubectl get secret --show-labels -l'
alias ksysgsecwsll='watch kubectl --namespace=kube-system get secret --show-labels -l'
alias kgnowsll='watch kubectl get nodes --show-labels -l'
alias kgnswsll='watch kubectl get namespaces --show-labels -l'
alias kgslwowidel='watch kubectl get --show-labels -o=wide -l'
alias ksysgslwowidel='watch kubectl --namespace=kube-system get --show-labels -o=wide -l'
alias kgposlwowidel='watch kubectl get pods --show-labels -o=wide -l'
alias ksysgposlwowidel='watch kubectl --namespace=kube-system get pods --show-labels -o=wide -l'
alias kgdepslwowidel='watch kubectl get deployment --show-labels -o=wide -l'
alias ksysgdepslwowidel='watch kubectl --namespace=kube-system get deployment --show-labels -o=wide -l'
alias kgstsslwowidel='watch kubectl get statefulset --show-labels -o=wide -l'
alias ksysgstsslwowidel='watch kubectl --namespace=kube-system get statefulset --show-labels -o=wide -l'
alias kgsvcslwowidel='watch kubectl get service --show-labels -o=wide -l'
alias ksysgsvcslwowidel='watch kubectl --namespace=kube-system get service --show-labels -o=wide -l'
alias kgingslwowidel='watch kubectl get ingress --show-labels -o=wide -l'
alias ksysgingslwowidel='watch kubectl --namespace=kube-system get ingress --show-labels -o=wide -l'
alias kgcmslwowidel='watch kubectl get configmap --show-labels -o=wide -l'
alias ksysgcmslwowidel='watch kubectl --namespace=kube-system get configmap --show-labels -o=wide -l'
alias kgsecslwowidel='watch kubectl get secret --show-labels -o=wide -l'
alias ksysgsecslwowidel='watch kubectl --namespace=kube-system get secret --show-labels -o=wide -l'
alias kgnoslwowidel='watch kubectl get nodes --show-labels -o=wide -l'
alias kgnsslwowidel='watch kubectl get namespaces --show-labels -o=wide -l'
alias kgwowidesll='watch kubectl get -o=wide --show-labels -l'
alias ksysgwowidesll='watch kubectl --namespace=kube-system get -o=wide --show-labels -l'
alias kgpowowidesll='watch kubectl get pods -o=wide --show-labels -l'
alias ksysgpowowidesll='watch kubectl --namespace=kube-system get pods -o=wide --show-labels -l'
alias kgdepwowidesll='watch kubectl get deployment -o=wide --show-labels -l'
alias ksysgdepwowidesll='watch kubectl --namespace=kube-system get deployment -o=wide --show-labels -l'
alias kgstswowidesll='watch kubectl get statefulset -o=wide --show-labels -l'
alias ksysgstswowidesll='watch kubectl --namespace=kube-system get statefulset -o=wide --show-labels -l'
alias kgsvcwowidesll='watch kubectl get service -o=wide --show-labels -l'
alias ksysgsvcwowidesll='watch kubectl --namespace=kube-system get service -o=wide --show-labels -l'
alias kgingwowidesll='watch kubectl get ingress -o=wide --show-labels -l'
alias ksysgingwowidesll='watch kubectl --namespace=kube-system get ingress -o=wide --show-labels -l'
alias kgcmwowidesll='watch kubectl get configmap -o=wide --show-labels -l'
alias ksysgcmwowidesll='watch kubectl --namespace=kube-system get configmap -o=wide --show-labels -l'
alias kgsecwowidesll='watch kubectl get secret -o=wide --show-labels -l'
alias ksysgsecwowidesll='watch kubectl --namespace=kube-system get secret -o=wide --show-labels -l'
alias kgnowowidesll='watch kubectl get nodes -o=wide --show-labels -l'
alias kgnswowidesll='watch kubectl get namespaces -o=wide --show-labels -l'
alias kgwslowidel='watch kubectl get --show-labels -o=wide -l'
alias ksysgwslowidel='watch kubectl --namespace=kube-system get --show-labels -o=wide -l'
alias kgpowslowidel='watch kubectl get pods --show-labels -o=wide -l'
alias ksysgpowslowidel='watch kubectl --namespace=kube-system get pods --show-labels -o=wide -l'
alias kgdepwslowidel='watch kubectl get deployment --show-labels -o=wide -l'
alias ksysgdepwslowidel='watch kubectl --namespace=kube-system get deployment --show-labels -o=wide -l'
alias kgstswslowidel='watch kubectl get statefulset --show-labels -o=wide -l'
alias ksysgstswslowidel='watch kubectl --namespace=kube-system get statefulset --show-labels -o=wide -l'
alias kgsvcwslowidel='watch kubectl get service --show-labels -o=wide -l'
alias ksysgsvcwslowidel='watch kubectl --namespace=kube-system get service --show-labels -o=wide -l'
alias kgingwslowidel='watch kubectl get ingress --show-labels -o=wide -l'
alias ksysgingwslowidel='watch kubectl --namespace=kube-system get ingress --show-labels -o=wide -l'
alias kgcmwslowidel='watch kubectl get configmap --show-labels -o=wide -l'
alias ksysgcmwslowidel='watch kubectl --namespace=kube-system get configmap --show-labels -o=wide -l'
alias kgsecwslowidel='watch kubectl get secret --show-labels -o=wide -l'
alias ksysgsecwslowidel='watch kubectl --namespace=kube-system get secret --show-labels -o=wide -l'
alias kgnowslowidel='watch kubectl get nodes --show-labels -o=wide -l'
alias kgnswslowidel='watch kubectl get namespaces --show-labels -o=wide -l'
alias kexn='kubectl exec -i -t --namespace'
alias klon='kubectl logs -f --namespace'
alias kpfn='kubectl port-forward --namespace'
alias kgn='kubectl get --namespace'
alias kdn='kubectl describe --namespace'
alias krmn='kubectl delete --namespace'
alias kgpon='kubectl get pods --namespace'
alias kdpon='kubectl describe pods --namespace'
alias krmpon='kubectl delete pods --namespace'
alias kgdepn='kubectl get deployment --namespace'
alias kddepn='kubectl describe deployment --namespace'
alias krmdepn='kubectl delete deployment --namespace'
alias kgstsn='kubectl get statefulset --namespace'
alias kdstsn='kubectl describe statefulset --namespace'
alias krmstsn='kubectl delete statefulset --namespace'
alias kgsvcn='kubectl get service --namespace'
alias kdsvcn='kubectl describe service --namespace'
alias krmsvcn='kubectl delete service --namespace'
alias kgingn='kubectl get ingress --namespace'
alias kdingn='kubectl describe ingress --namespace'
alias krmingn='kubectl delete ingress --namespace'
alias kgcmn='kubectl get configmap --namespace'
alias kdcmn='kubectl describe configmap --namespace'
alias krmcmn='kubectl delete configmap --namespace'
alias kgsecn='kubectl get secret --namespace'
alias kdsecn='kubectl describe secret --namespace'
alias krmsecn='kubectl delete secret --namespace'
alias kgoyamln='kubectl get -o=yaml --namespace'
alias kgpooyamln='kubectl get pods -o=yaml --namespace'
alias kgdepoyamln='kubectl get deployment -o=yaml --namespace'
alias kgstsoyamln='kubectl get statefulset -o=yaml --namespace'
alias kgsvcoyamln='kubectl get service -o=yaml --namespace'
alias kgingoyamln='kubectl get ingress -o=yaml --namespace'
alias kgcmoyamln='kubectl get configmap -o=yaml --namespace'
alias kgsecoyamln='kubectl get secret -o=yaml --namespace'
alias kgowiden='kubectl get -o=wide --namespace'
alias kgpoowiden='kubectl get pods -o=wide --namespace'
alias kgdepowiden='kubectl get deployment -o=wide --namespace'
alias kgstsowiden='kubectl get statefulset -o=wide --namespace'
alias kgsvcowiden='kubectl get service -o=wide --namespace'
alias kgingowiden='kubectl get ingress -o=wide --namespace'
alias kgcmowiden='kubectl get configmap -o=wide --namespace'
alias kgsecowiden='kubectl get secret -o=wide --namespace'
alias kgojsonn='kubectl get -o=json --namespace'
alias kgpoojsonn='kubectl get pods -o=json --namespace'
alias kgdepojsonn='kubectl get deployment -o=json --namespace'
alias kgstsojsonn='kubectl get statefulset -o=json --namespace'
alias kgsvcojsonn='kubectl get service -o=json --namespace'
alias kgingojsonn='kubectl get ingress -o=json --namespace'
alias kgcmojsonn='kubectl get configmap -o=json --namespace'
alias kgsecojsonn='kubectl get secret -o=json --namespace'
alias kgsln='kubectl get --show-labels --namespace'
alias kgposln='kubectl get pods --show-labels --namespace'
alias kgdepsln='kubectl get deployment --show-labels --namespace'
alias kgstssln='kubectl get statefulset --show-labels --namespace'
alias kgsvcsln='kubectl get service --show-labels --namespace'
alias kgingsln='kubectl get ingress --show-labels --namespace'
alias kgcmsln='kubectl get configmap --show-labels --namespace'
alias kgsecsln='kubectl get secret --show-labels --namespace'
alias kgwn='watch kubectl get --namespace'
alias kgpown='watch kubectl get pods --namespace'
alias kgdepwn='watch kubectl get deployment --namespace'
alias kgstswn='watch kubectl get statefulset --namespace'
alias kgsvcwn='watch kubectl get service --namespace'
alias kgingwn='watch kubectl get ingress --namespace'
alias kgcmwn='watch kubectl get configmap --namespace'
alias kgsecwn='watch kubectl get secret --namespace'
alias kgwoyamln='watch kubectl get -o=yaml --namespace'
alias kgpowoyamln='watch kubectl get pods -o=yaml --namespace'
alias kgdepwoyamln='watch kubectl get deployment -o=yaml --namespace'
alias kgstswoyamln='watch kubectl get statefulset -o=yaml --namespace'
alias kgsvcwoyamln='watch kubectl get service -o=yaml --namespace'
alias kgingwoyamln='watch kubectl get ingress -o=yaml --namespace'
alias kgcmwoyamln='watch kubectl get configmap -o=yaml --namespace'
alias kgsecwoyamln='watch kubectl get secret -o=yaml --namespace'
alias kgowidesln='kubectl get -o=wide --show-labels --namespace'
alias kgpoowidesln='kubectl get pods -o=wide --show-labels --namespace'
alias kgdepowidesln='kubectl get deployment -o=wide --show-labels --namespace'
alias kgstsowidesln='kubectl get statefulset -o=wide --show-labels --namespace'
alias kgsvcowidesln='kubectl get service -o=wide --show-labels --namespace'
alias kgingowidesln='kubectl get ingress -o=wide --show-labels --namespace'
alias kgcmowidesln='kubectl get configmap -o=wide --show-labels --namespace'
alias kgsecowidesln='kubectl get secret -o=wide --show-labels --namespace'
alias kgslowiden='kubectl get --show-labels -o=wide --namespace'
alias kgposlowiden='kubectl get pods --show-labels -o=wide --namespace'
alias kgdepslowiden='kubectl get deployment --show-labels -o=wide --namespace'
alias kgstsslowiden='kubectl get statefulset --show-labels -o=wide --namespace'
alias kgsvcslowiden='kubectl get service --show-labels -o=wide --namespace'
alias kgingslowiden='kubectl get ingress --show-labels -o=wide --namespace'
alias kgcmslowiden='kubectl get configmap --show-labels -o=wide --namespace'
alias kgsecslowiden='kubectl get secret --show-labels -o=wide --namespace'
alias kgwowiden='watch kubectl get -o=wide --namespace'
alias kgpowowiden='watch kubectl get pods -o=wide --namespace'
alias kgdepwowiden='watch kubectl get deployment -o=wide --namespace'
alias kgstswowiden='watch kubectl get statefulset -o=wide --namespace'
alias kgsvcwowiden='watch kubectl get service -o=wide --namespace'
alias kgingwowiden='watch kubectl get ingress -o=wide --namespace'
alias kgcmwowiden='watch kubectl get configmap -o=wide --namespace'
alias kgsecwowiden='watch kubectl get secret -o=wide --namespace'
alias kgwojsonn='watch kubectl get -o=json --namespace'
alias kgpowojsonn='watch kubectl get pods -o=json --namespace'
alias kgdepwojsonn='watch kubectl get deployment -o=json --namespace'
alias kgstswojsonn='watch kubectl get statefulset -o=json --namespace'
alias kgsvcwojsonn='watch kubectl get service -o=json --namespace'
alias kgingwojsonn='watch kubectl get ingress -o=json --namespace'
alias kgcmwojsonn='watch kubectl get configmap -o=json --namespace'
alias kgsecwojsonn='watch kubectl get secret -o=json --namespace'
alias kgslwn='watch kubectl get --show-labels --namespace'
alias kgposlwn='watch kubectl get pods --show-labels --namespace'
alias kgdepslwn='watch kubectl get deployment --show-labels --namespace'
alias kgstsslwn='watch kubectl get statefulset --show-labels --namespace'
alias kgsvcslwn='watch kubectl get service --show-labels --namespace'
alias kgingslwn='watch kubectl get ingress --show-labels --namespace'
alias kgcmslwn='watch kubectl get configmap --show-labels --namespace'
alias kgsecslwn='watch kubectl get secret --show-labels --namespace'
alias kgwsln='watch kubectl get --show-labels --namespace'
alias kgpowsln='watch kubectl get pods --show-labels --namespace'
alias kgdepwsln='watch kubectl get deployment --show-labels --namespace'
alias kgstswsln='watch kubectl get statefulset --show-labels --namespace'
alias kgsvcwsln='watch kubectl get service --show-labels --namespace'
alias kgingwsln='watch kubectl get ingress --show-labels --namespace'
alias kgcmwsln='watch kubectl get configmap --show-labels --namespace'
alias kgsecwsln='watch kubectl get secret --show-labels --namespace'
alias kgslwowiden='watch kubectl get --show-labels -o=wide --namespace'
alias kgposlwowiden='watch kubectl get pods --show-labels -o=wide --namespace'
alias kgdepslwowiden='watch kubectl get deployment --show-labels -o=wide --namespace'
alias kgstsslwowiden='watch kubectl get statefulset --show-labels -o=wide --namespace'
alias kgsvcslwowiden='watch kubectl get service --show-labels -o=wide --namespace'
alias kgingslwowiden='watch kubectl get ingress --show-labels -o=wide --namespace'
alias kgcmslwowiden='watch kubectl get configmap --show-labels -o=wide --namespace'
alias kgsecslwowiden='watch kubectl get secret --show-labels -o=wide --namespace'
alias kgwowidesln='watch kubectl get -o=wide --show-labels --namespace'
alias kgpowowidesln='watch kubectl get pods -o=wide --show-labels --namespace'
alias kgdepwowidesln='watch kubectl get deployment -o=wide --show-labels --namespace'
alias kgstswowidesln='watch kubectl get statefulset -o=wide --show-labels --namespace'
alias kgsvcwowidesln='watch kubectl get service -o=wide --show-labels --namespace'
alias kgingwowidesln='watch kubectl get ingress -o=wide --show-labels --namespace'
alias kgcmwowidesln='watch kubectl get configmap -o=wide --show-labels --namespace'
alias kgsecwowidesln='watch kubectl get secret -o=wide --show-labels --namespace'
alias kgwslowiden='watch kubectl get --show-labels -o=wide --namespace'
alias kgpowslowiden='watch kubectl get pods --show-labels -o=wide --namespace'
alias kgdepwslowiden='watch kubectl get deployment --show-labels -o=wide --namespace'
alias kgstswslowiden='watch kubectl get statefulset --show-labels -o=wide --namespace'
alias kgsvcwslowiden='watch kubectl get service --show-labels -o=wide --namespace'
alias kgingwslowiden='watch kubectl get ingress --show-labels -o=wide --namespace'
alias kgcmwslowiden='watch kubectl get configmap --show-labels -o=wide --namespace'
alias kgsecwslowiden='watch kubectl get secret --show-labels -o=wide --namespace'
