---
name: Build
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  builds:
    name: Build on ${{ matrix.system }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            os: ubuntu-latest
          - system: aarch64-darwin
            os: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check nix flake dev inputs
        uses: DeterminateSystems/flake-checker-action@v12
        with:
          flake-lock-path: modules/meta/_dev/flake.lock
      - name: Check nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v12
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: icyd
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Setup SSH agent
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh-agent -a "$SSH_AUTH_SOCK" >/dev/null
          echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass
          chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | \
            DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add >/dev/null
      - name: Build system configuration
        run: nix flake check
