---
name: Update flake inputs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Update dev flake.lock
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          path-to-flake-dir: modules/meta/_dev
          pr-title: Update nix flake dev inputs
          pr-labels: |
            dependencies
            automated
            merge-queue
      - name: Setup SSH agent
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh-agent -a "$SSH_AUTH_SOCK" >/dev/null
          echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass
          chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | \
            DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add >/dev/null
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          pr-title: Update nix flake inputs
          pr-labels: |
            dependencies
            automated
            merge-queue
