---
name: Update flake inputs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "SSH: configure agent"
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "SSH: trust host"
        run: |
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
      - uses: cachix/install-nix-action@v31
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          pr-title: Update nix flake inputs
          pr-labels: |
            dependencies
            automated
            merge-queue
